# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Mar 27 07:04:56 2023
# ------------------------------------------------

package:
  name: webcolors
  version: '1.13'
source:
  fn: webcolors-1.13.tar.gz
  sha256: c225b674c83fa923be93d235330ce0300373d02885cef23238813b0d5668304a
  url: https://pypi.io/packages/source/w/webcolors/webcolors-1.13.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/webcolors_1679900785843/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.1.0 h0b41bf4_0
    - pip 23.0.1 pyhd8ed1ab_0
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 67.6.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023b h71feb2d_0
    - wheel 0.40.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.5
test:
  imports:
    - webcolors
about:
  home: https://github.com/ubernostrum/webcolors
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Library for working with HTML/CSS color formats in Python.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
