# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: libglib
  version: 2.80.2
source:
  patches:
    - crossplatform-test-tweaks.patch
    - hardcoded-paths.patch
  sha256: b9cfb6f7a5bd5b31238fd5d56df226b2dda5ea37611475bf89f6a0f9400fe8bd
  url: https://download.gnome.org/sources/glib/2.80/glib-2.80.2.tar.xz
build:
  ignore_run_exports_from:
    - gxx_linux-64 12.*
    - python *
  number: 1
  run_exports:
    - libglib >=2.80.2,<3.0a0
  string: h8a4344b_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_4
    - binutils_linux-64 2.40 hb3c18ed_7
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - gcc_impl_linux-64 12.3.0 h58ffeeb_10
    - gcc_linux-64 12.3.0 h6b3dd4b_7
    - gettext-tools 0.22.5 h59595ed_2
    - gxx_impl_linux-64 12.3.0 h2a574ab_10
    - gxx_linux-64 12.3.0 ha28b414_7
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_4
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-devel_linux-64 12.3.0 h6b66f73_110
    - libgcc-ng 13.2.0 h77fa898_10
    - libgomp 13.2.0 h77fa898_10
    - libnsl 2.0.1 hd590300_0
    - libsanitizer 12.3.0 hb8811af_10
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-devel_linux-64 12.3.0 h6b66f73_110
    - libstdcxx-ng 13.2.0 hc0a3c3a_10
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - meson 1.4.0 pyhd8ed1ab_0
    - ncurses 6.5 h59595ed_0
    - ninja 1.12.1 h297d8ca_0
    - openssl 3.3.1 h4ab18f5_0
    - packaging 24.1 pyhd8ed1ab_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - sysroot_linux-64 2.12 he073ed8_17
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_10
    - libgomp 13.2.0 h77fa898_10
    - libiconv 1.17 hd590300_2
    - libzlib 1.3.1 h4ab18f5_1
    - pcre2 10.44 h0f59acf_0
    - zlib 1.3.1 h4ab18f5_1
  run:
    - libffi >=3.4,<4.0a0
    - libgcc-ng >=12
    - libiconv >=1.17,<2.0a0
    - libzlib >=1.3.1,<2.0a0
    - pcre2 >=10.44,<10.45.0a0
  run_constrained:
    - glib 2.80.2 *_1
test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0.so.0
    - test ! -f ${PREFIX}/lib/libgobject-2.0.la
    - test ! -f ${PREFIX}/lib/libglib-2.0${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/glib-2.0.pc
    - test -f ${PREFIX}/etc/conda/activate.d/libglib_activate.sh
    - test -f ${PREFIX}/etc/conda/deactivate.d/libglib_deactivate.sh
    - test -f ${PREFIX}/share/gir-1.0/GLib-2.0.gir
    - test -f ${PREFIX}/lib/girepository-1.0/GLib-2.0.typelib
about:
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Provides core application building blocks for libraries and applications
    written in C.
extra:
  copy_test_source_files: true
  feedstock-name: glib
  final: true
  flow_run_id: azure_20240616.1.1
  recipe-maintainers:
    - ccordoba12
    - isuruf
    - jakirkham
    - ocefpaf
    - pkgw
    - scopatz
    - tschoonj
    - xhochy
  remote_url: https://github.com/conda-forge/glib-feedstock
  sha: 5a85af0a119dd44adbc626b35173d80ba6e858c1
