# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Dec  2 17:43:48 2021
# ------------------------------------------------

package:
  name: pybtex
  version: 0.24.0
source:
  patches:
    - backport_37.patch
  sha256: 818eae35b61733e5c007c3fcd2cfb75ed1bc8b4173c1f70b56cc4c0802d34755
  url: https://pypi.io/packages/source/p/pybtex/pybtex-0.24.0.tar.gz
build:
  entry_points:
    - pybtex = pybtex.__main__:main
    - pybtex-convert = pybtex.database.convert.__main__:main
    - pybtex-format = pybtex.database.format.__main__:main
  noarch: python
  number: '2'
  script: /home/conda/feedstock_root/build_artifacts/pybtex_1638467081712/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_2
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgomp 11.2.0 h1d223b6_11
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h36c2ea0_1013
    - ncurses 6.2 h58526e2_4
    - openssl 3.0.0 h7f98852_2
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.10.0 h543edf9_3_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 59.4.0 py310hff52083_0
    - sqlite 3.37.0 h9cd32fc_0
    - tk 8.6.11 h27826a3_1
    - tzdata 2021e he74cb21_0
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - latexcodec >=1.0.4
    - python >=3.6
    - pyyaml >=3.01
    - setuptools
    - six
test:
  commands:
    - pip check
    - pybtex --help
    - pybtex-convert --help
    - pybtex-format --help
  imports:
    - pybtex
    - pybtex.backends
    - pybtex.bibtex
    - pybtex.charwidths
    - pybtex.database
    - pybtex.database.convert
    - pybtex.database.format
    - pybtex.database.input
    - pybtex.database.output
    - pybtex.markup
    - pybtex.plugin
    - pybtex.style
    - pybtex.style.formatting
    - pybtex.style.labels
    - pybtex.style.names
    - pybtex.style.sorting
  requires:
    - pip
about:
  description: Pybtex reads citation information from a file and produces a formatted
    bibliography. BibTeX style files are supported. Alternatively it is possible to
    write styles in Python.
  dev_url: https://bitbucket.org/pybtex-devs/pybtex/
  doc_url: http://pythonhosted.org/pybtex/
  home: https://pybtex.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A BibTeX-compatible bibliography processor in Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - croth1
    - ocefpaf
