# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Mar 18 23:46:02 2024
# ------------------------------------------------

package:
  name: jupyter_events
  version: 0.10.0
source:
  sha256: 670b8229d3cc882ec782144ed22e0d29e1c2d639263f92ca8383e66682845e22
  url: https://pypi.io/packages/source/j/jupyter-events/jupyter_events-0.10.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/jupyter_events_1710805637316/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatchling 1.22.2 pyhd8ed1ab_0
    - importlib-metadata 7.0.2 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.3.3 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - jsonschema-with-format-nongpl >=4.18.0
    - python >=3.8
    - python-json-logger >=2.0.4
    - pyyaml >=5.3
    - referencing
    - rfc3339-validator
    - rfc3986-validator >=0.1.1
    - traitlets >=5.3
about:
  dev_url: https://github.com/jupyter/jupyter_events
  doc_url: https://jupyter-events.readthedocs.io
  home: https://pypi.org/project/jupyter-events
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Event System library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240318.4.1
  recipe-maintainers:
    - Zsailer
    - afshin
    - blink1073
    - bollwyvl
  remote_url: https://github.com/conda-forge/jupyter_events-feedstock
  sha: 03f2d3cb1c3e916926f92af9546a816f35e3072d
