# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Feb  7 15:22:03 2024
# ------------------------------------------------

package:
  name: syrupy
  version: 4.6.1
source:
  sha256: 37a835c9ce7857eeef86d62145885e10b3cb9615bc6abeb4ce404b3f18e1bb36
  url: https://pypi.io/packages/source/s/syrupy/syrupy-4.6.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/syrupy_1707319418074/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - pip 24.0 pyhd8ed1ab_0
    - poetry-core 1.9.0 pyhd8ed1ab_0
    - python 3.12.1 hab00c5b_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - pytest >=7.0.0,<9.0.0
    - python >=3.8.1,<4.0
test:
  commands:
    - pip check
  imports:
    - syrupy
  requires:
    - pip
about:
  home: https://github.com/tophat/syrupy
  license: Apache-2.0
  license_file: LICENSE
  summary: Pytest Snapshot Test Utility
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240207.7.1
  recipe-maintainers:
    - ludaavics
    - noahnu
  remote_url: https://github.com/conda-forge/syrupy-feedstock
  sha: e25b34157a55143702f2ee113310d82be9c38ee1
