# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri May 31 02:19:45 2024
# ------------------------------------------------

package:
  name: jupyter_server
  version: 2.14.1
source:
  sha256: 12558d158ec7a0653bf96cc272bc7ad79e0127d503b982ed144399346694f726
  url:
    - https://github.com/jupyter-server/jupyter_server/releases/download/v2.14.1/jupyter_server-2.14.1.tar.gz
    - https://pypi.io/packages/source/j/jupyter-server/jupyter_server-2.14.1.tar.gz
build:
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main
  noarch: python
  number: '0'
  script:
    - /home/conda/feedstock_root/build_artifacts/jupyter_server_1717122053158/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
      -m pip install . -vv --no-deps --no-cache-dir --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-jupyter-builder 0.9.1 pyhd8ed1ab_0
    - hatchling 1.24.2 pyhd8ed1ab_0
    - icu 73.2 h59595ed_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 hf3520f5_1
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libuuid 2.38.1 h0b41bf4_0
    - libuv 1.48.0 hd590300_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 h4ab18f5_6
    - ncurses 6.5 h59595ed_0
    - nodejs 20.12.2 hb753e55_0
    - openssl 3.3.0 h4ab18f5_3
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.5.22 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
    - zlib 1.2.13 h4ab18f5_6
  run:
    - anyio >=3.1.0
    - argon2-cffi
    - jinja2
    - jupyter_client >=7.4.4
    - jupyter_core >=4.12,!=5.0.*
    - jupyter_events >=0.9.0
    - jupyter_server_terminals
    - nbconvert-core >=6.4.4
    - nbformat >=5.3.0
    - overrides
    - packaging
    - prometheus_client
    - python >=3.8
    - pyzmq >=24
    - send2trash >=1.8.2
    - terminado >=0.8.3
    - tornado >=6.2.0
    - traitlets >=5.6.0
    - websocket-client
test:
  commands:
    - pip check
    - jupyter server -h
    - jupyter-server -h
  downstreams:
    - jupyterlab >=3.2
    - jupyterlab_server >=2.20.0
  imports:
    - jupyter_server
  requires:
    - coverage
    - flaky
    - ipykernel
    - pip
    - pytest >=7.0,<8
    - pytest-console-scripts
    - pytest-cov
    - pytest-jupyter-server >=0.7
    - pytest-timeout
    - requests
  source_files:
    - tests
about:
  dev_url: https://github.com/jupyter/jupyter_server
  home: https://jupyter-server.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "The backend\u2014i.e. core services, APIs, and REST endpoints to Jupyter\
    \ web applications."
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240530.4.1
  recipe-maintainers:
    - SylvainCorlay
    - Zsailer
    - blink1073
    - bollwyvl
    - jasongrout
    - maartenbreddels
    - minrk
  remote_url: https://github.com/conda-forge/jupyter_server-feedstock
  sha: ca23e5ea877319b09c541d0eaa66225c1ca055bf
