# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Dec  3 23:51:34 2023
# ------------------------------------------------

package:
  name: lcms2
  version: '2.16'
source:
  patches:
    - win_jpegturbo.patch
  sha256: d873d34ad8b9b4cea010631f1a6228d2087475e4dc5e763eb81acc23d9d45a51
  url: https://github.com/mm2/Little-CMS/releases/download/lcms2.16/lcms2-2.16.tar.gz
build:
  number: '0'
  run_exports:
    - lcms2 >=2.16,<3.0a0
  string: hb7c19ff_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_3
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_103
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libsanitizer 12.3.0 h0f45ef3_3
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - libtool 2.4.7 h27087fc_0
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - lerc 4.0.0 h27087fc_0
    - libdeflate 1.19 hd590300_0
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libjpeg-turbo 3.0.0 hd590300_1
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - libtiff 4.6.0 ha9c0a0a_2
    - libwebp-base 1.3.2 hd590300_0
    - libzlib 1.2.13 hd590300_5
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.5 hfc55251_0
  run:
    - libgcc-ng >=12
    - libjpeg-turbo >=3.0.0,<4.0a0
    - libtiff >=4.6.0,<4.7.0a0
test:
  commands:
    - test -f ${PREFIX}/include/lcms2.h
    - test ! -f ${PREFIX}/lib/liblcms2.a
    - test -f ${PREFIX}/lib/liblcms2${SHLIB_EXT}
    - jpgicc
    - tificc
    - linkicc
    - transicc
    - psicc
about:
  home: http://www.littlecms.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open Source Color Management Engine
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231203.3.1
  recipe-maintainers:
    - hmaarrfk
    - isuruf
  remote_url: https://github.com/conda-forge/lcms2-feedstock
  sha: d2e58a917308df1ca5ed790ffc695a1b18eecc5b
