# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Sep 13 14:59:25 2023
# ------------------------------------------------

package:
  name: pkgutil-resolve-name
  version: 1.3.10
source:
  sha256: 357d6c9e6a755653cfd78893817c0853af365dd51ec97f3d358a819373bbd174
  url: https://pypi.io/packages/source/p/pkgutil-resolve-name/pkgutil_resolve_name-1.3.10.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1694617248815/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_0
    - libgomp 13.2.0 h807b86a_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.43.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.11.5 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - pkgutil_resolve_name
  requires:
    - pip
about:
  doc_url: https://docs.python.org/3.9/library/pkgutil.html#pkgutil.resolve_name
  home: https://github.com/graingert/pkgutil-resolve-name
  license: MIT AND PSF-2.0
  license_file: LICENSE
  summary: Backport of Python 3.9's pkgutil.resolve_name; resolves a name to an object.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - thewchan
