# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Mar 23 18:14:44 2024
# ------------------------------------------------

package:
  name: libtiff
  version: 4.6.0
source:
  patches:
    - patches/use_unix_io.patch
  sha256: 88b3979e6d5c7e32b50d7ec72fb15af724f6ab2cbf7e10880c360a77e4b5d99a
  url: https://download.osgeo.org/libtiff/tiff-4.6.0.tar.gz
build:
  missing_dso_whitelist:
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib
  number: '3'
  run_exports:
    - libtiff >=4.6.0,<4.7.0a0
  string: h1dd3fc0_3
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 he2b93b0_5
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsanitizer 12.3.0 h0f45ef3_5
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_105
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libtool 2.4.7 h27087fc_0
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - lerc 4.0.0 h27087fc_0
    - libdeflate 1.20 hd590300_0
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libjpeg-turbo 3.0.0 hd590300_1
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libwebp-base 1.3.2 hd590300_0
    - libzlib 1.2.13 hd590300_5
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
    - zstd 1.5.5 hfc55251_0
  run:
    - lerc >=4.0.0,<5.0a0
    - libdeflate >=1.20,<1.21.0a0
    - libgcc-ng >=12
    - libjpeg-turbo >=3.0.0,<4.0a0
    - libstdcxx-ng >=12
    - libwebp-base >=1.3.2,<2.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - xz >=5.2.6,<6.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - test ! -f ${PREFIX}/lib/libtiff.a
    - test ! -f ${PREFIX}/lib/libtiffxx.a
    - test -f ${PREFIX}/lib/libtiff.so
    - test -f ${PREFIX}/lib/libtiffxx.so
about:
  description: 'This software provides support for the Tag Image File Format (TIFF),
    a

    widely used format for storing image data.

    '
  doc_url: http://www.libtiff.org/document.html
  home: http://www.libtiff.org/
  license: HPND
  license_file: LICENSE.md
  summary: Support for the Tag Image File Format (TIFF).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240323.2.1
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
  remote_url: https://github.com/conda-forge/libtiff-feedstock
  sha: 27f425d5dc7e0607feb521393fc5cf0bf1e71b4d
