# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 26 22:24:08 2023
# ------------------------------------------------

package:
  name: libxcb
  version: '1.16'
source:
  fn: libxcb-1.16.tar.bz2
  patches: null
  sha256: bc0f75f84b28e6496a19a1d094d7e47def861a50cb7cce5b23b62eecdc2a4479
  url: https://xorg.freedesktop.org/archive/individual/lib/libxcb-1.16.tar.gz
build:
  detect_binary_files_with_prefix: true
  number: '0'
  run_exports:
    - libxcb >=1.16,<1.17.0a0
  string: hd590300_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_1
    - gcc_impl_linux-64 12.3.0 he2b93b0_0
    - gcc_linux-64 12.3.0 h76fc315_1
    - gettext 0.21.1 h27087fc_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_0
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 12.3.0 h0f45ef3_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libtool 2.4.7 h27087fc_0
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 4_hd590300_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.43.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - python 3.11.4 hab00c5b_0_cpython
    - python_abi 3.11 3_cp311
    - readline 8.2 h8228510_1
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - xcb-proto 1.16.0 py311h459d7ec_0
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-util-macros 1.19.3 h7f98852_0
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - pthread-stubs
    - xorg-libxau >=1.0.11,<2.0a0
    - xorg-libxdmcp
test:
  commands:
    - test -f $PREFIX/lib/libxcb.so
    - test -f $PREFIX/lib/libxcb-composite.so
    - test -f $PREFIX/lib/libxcb-damage.so
    - test -f $PREFIX/lib/libxcb-dpms.so
    - test -f $PREFIX/lib/libxcb-dri2.so
    - test -f $PREFIX/lib/libxcb-glx.so
    - test -f $PREFIX/lib/libxcb-present.so
    - test -f $PREFIX/lib/libxcb-randr.so
    - test -f $PREFIX/lib/libxcb-record.so
    - test -f $PREFIX/lib/libxcb-res.so
    - test -f $PREFIX/lib/libxcb-screensaver.so
    - test -f $PREFIX/lib/libxcb-shape.so
    - test -f $PREFIX/lib/libxcb-shm.so
    - test -f $PREFIX/lib/libxcb-sync.so
    - test -f $PREFIX/lib/libxcb-xf86dri.so
    - test -f $PREFIX/lib/libxcb-xfixes.so
    - test -f $PREFIX/lib/libxcb-xinerama.so
    - test -f $PREFIX/lib/libxcb-xkb.so
    - test -f $PREFIX/lib/libxcb-xtest.so
    - test -f $PREFIX/lib/libxcb-xv.so
    - test -f $PREFIX/lib/libxcb-xvmc.so
    - test -f $PREFIX/lib/libxcb-dri3.so
    - test -f $PREFIX/lib/libxcb-render.so
    - test -f $PREFIX/lib/libxcb-xinput.so
about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is the C-language Binding (XCB) package to the X Window System protocol
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw
