CI: azure
c_compiler: gcc
c_compiler_version: '12'
c_stdlib: sysroot
c_stdlib_version: '2.12'
cdt_name: cos6
channel_sources: conda-forge/label/numpy_rc,conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '12'
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
extend_keys:
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
mkl: '2023'
mkl_devel: '2023'
mkl_support: nomkl
numpy: '2.0'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: 3.10.* *_cpython
python_impl: cpython
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - python
  - numpy
  - python_impl
- - c_compiler_version
  - cxx_compiler_version
- - c_stdlib_version
  - cdt_name
