# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat May  4 18:18:18 2024
# ------------------------------------------------

package:
  name: pygments
  version: 2.18.0
source:
  sha256: 786ff802f32e91311bff3889f6e9a86e81505fe99f2735bb6d60ae0c5004f199
  url: https://pypi.io/packages/source/p/pygments/pygments-2.18.0.tar.gz
build:
  entry_points:
    - pygmentize = pygments.cmdline:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pygments_1714846767233/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatchling 1.24.2 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_6
    - libgomp 13.2.0 h77fa898_6
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.3.0 hd590300_0
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.4.10 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
    - pygmentize -h
  imports:
    - pygments
    - pygments.filters
    - pygments.formatters
    - pygments.lexers
    - pygments.plugin
    - pygments.styles
  requires:
    - pip
about:
  home: http://pygments.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Pygments is a generic syntax highlighter suitable for use in code hosting,
    forums, wikis or other applications that need to prettify source code.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240504.3.1
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - scopatz
  remote_url: https://github.com/conda-forge/pygments-feedstock
  sha: f7e1a3939523805c62f58b60660435584a4a60c2
