# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Mar 11 05:30:39 2024
# ------------------------------------------------

package:
  name: pytest-doctestplus
  version: 1.2.1
source:
  sha256: 2472a8a2c8cea34d2f65f6499543faeb748eecb59c597852fd98839b47307679
  url: https://pypi.io/packages/source/p/pytest-doctestplus/pytest-doctestplus-1.2.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pytest-doctestplus_1710135124366/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.1 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.1 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.1.1 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - setuptools_scm 8.0.4 hd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.10.0 hd8ed1ab_0
    - typing_extensions 4.10.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - packaging >=17.0
    - pip
    - pytest >=4.6
    - python >=3.8
    - setuptools >=30.3
test:
  commands:
    - pip check
  imports:
    - pytest_doctestplus
  requires:
    - pip
about:
  description: 'This package contains a plugin for the pytest framework that provides

    advanced doctest support and enables the testing of reStructuredText files.

    '
  dev_url: https://github.com/scientific-python/pytest-doctestplus
  doc_url: https://pypi.org/project/pytest-doctestplus/
  home: https://github.com/scientific-python/pytest-doctestplus
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Pytest plugin with advanced doctest features.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240311.1.1
  recipe-maintainers:
    - anthchirp
    - astrofrog
    - bsipocz
    - mwcraig
    - pllim
  remote_url: https://github.com/conda-forge/pytest-doctestplus-feedstock
  sha: bb9de74c9fbe89ca5c67aea704aa2da0094c318b
