# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Mar 21 17:06:48 2024
# ------------------------------------------------

package:
  name: importlib_resources
  version: 6.4.0
source:
  sha256: cdb2b453b8046ca4e3798eb1d84f3cce1446a0e8e7b5ef4efb600f19fc398145
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-6.4.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/importlib_resources_1711040877059/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_1
    - setuptools_scm 8.0.4 hd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - toml 0.10.2 pyhd8ed1ab_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.10.0 hd8ed1ab_0
    - typing_extensions 4.10.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
    - zipp >=3.1.0
  run_constrained:
    - importlib-resources >=6.4.0,<6.4.1.0a0
test:
  commands:
    - pip check
  imports:
    - importlib_resources
  requires:
    - pip
about:
  home: http://importlib-resources.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: Backport of Python 3.7's standard library `importlib.resources`
extra:
  copy_test_source_files: true
  feedstock-name: importlib_resources
  final: true
  flow_run_id: azure_20240321.2.1
  recipe-maintainers:
    - ocefpaf
  remote_url: https://github.com/conda-forge/importlib_resources-feedstock
  sha: bca1d18aa653280a6f6690d4b7c55b5f2d946906
