# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Sep 24 07:06:31 2023
# ------------------------------------------------

package:
  name: pybtex-docutils
  version: 1.0.3
source:
  fn: pybtex-docutils-1.0.3.tar.gz
  sha256: 3a7ebdf92b593e00e8c1c538aa9a20bca5d92d84231124715acc964d51d93c6b
  url: https://pypi.io/packages/source/p/pybtex-docutils/pybtex-docutils-1.0.3.tar.gz
build:
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/pybtex-docutils_1695539270195/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: py312h7900ff3_1
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - docutils 0.20.1 py312h7900ff3_2
    - latexcodec 2.0.1 pyh9f0ad1d_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.43.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.3 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pybtex 0.24.0 pyhd8ed1ab_2
    - python 3.12.0rc3 rc3_h124a313_0_cpython
    - python_abi 3.12 4_cp312
    - pyyaml 6.0.1 py312h98912ed_1
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - tk 8.6.13 h2797004_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - yaml 0.2.5 h7f98852_2
  run:
    - docutils >=0.14
    - pybtex >=0.16
    - python >=3.12.0rc3,<3.13.0a0
    - python_abi 3.12.* *_cp312
    - setuptools
test:
  commands:
    - python -c "import pybtex.plugin; pybtex.plugin.find_plugin('pybtex.backends',
      'docutils')()"
  imports:
    - pybtex
    - pybtex.plugin
  requires:
    - pip
about:
  description: A docutils backend for pybtex.
  dev_url: https://github.com/mcmtroffaes/pybtex-docutils
  doc_url: http://pybtex-docutils.readthedocs.org/
  home: https://github.com/mcmtroffaes/pybtex-docutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A docutils backend for pybtex.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - croth1
