# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun 12 10:48:44 2024
# ------------------------------------------------

package:
  name: packaging
  version: '24.1'
source:
  sha256: 026ed72c8ed3fcce5bf8950572258698927fd1dbda10a5e981cdf0ac37f4f002
  url: https://pypi.io/packages/source/p/packaging/packaging-24.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/packaging_1718189413536/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotli-python 1.1.0 py312h30efb56_1
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - certifi 2024.6.2 pyhd8ed1ab_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - docutils 0.21.2 pyhd8ed1ab_0
    - flit 3.9.0 pyhd8ed1ab_1
    - flit-core 3.9.0 pyhd8ed1ab_1
    - idna 3.7 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 hf3520f5_3
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pip 24.0 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.12.3 hab00c5b_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - requests 2.32.3 pyhd8ed1ab_0
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli-w 1.0.0 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - urllib3 2.2.1 pyhd8ed1ab_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
  imports:
    - packaging
  requires:
    - pip
about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240612.1.1
  recipe-maintainers:
    - jakirkham
    - nicoddemus
  remote_url: https://github.com/conda-forge/packaging-feedstock
  sha: cb221f4bb820b37eaaa7d711280efdb20ad80714
