# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jun 14 00:15:21 2024
# ------------------------------------------------

package:
  name: llvmlite
  version: 0.43.0
source:
  sha256: ae2b5b5c3ef67354824fb75517c8db5fbe93bc02cd9671f3c62271626bc041d5
  url: https://pypi.io/packages/source/l/llvmlite/llvmlite-0.43.0.tar.gz
build:
  number: '0'
  script_env:
    - PY_VCRUNTIME_REDIST
  string: py312h9c5d478_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_3
    - binutils_linux-64 2.40 hb3c18ed_6
    - bzip2 1.0.8 hd590300_5
    - c-ares 1.28.1 hd590300_0
    - ca-certificates 2024.6.2 hbcca054_0
    - cmake 3.29.5 hcafd917_0
    - gcc_impl_linux-64 12.3.0 h58ffeeb_8
    - gcc_linux-64 12.3.0 h6b3dd4b_6
    - gxx_impl_linux-64 12.3.0 h2a574ab_8
    - gxx_linux-64 12.3.0 ha28b414_6
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 hf3520f5_3
    - libcurl 8.8.0 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.2 h59595ed_0
    - libgcc-devel_linux-64 12.3.0 h6b66f73_108
    - libgcc-ng 13.2.0 h77fa898_8
    - libgomp 13.2.0 h77fa898_8
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 12.3.0 hb8811af_8
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-devel_linux-64 12.3.0 h6b66f73_108
    - libstdcxx-ng 13.2.0 hc0a3c3a_8
    - libuv 1.48.0 hd590300_0
    - libzlib 1.3.1 h4ab18f5_1
    - make 4.3 hd18ef5c_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.12 he073ed8_17
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_3
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_8
    - libgomp 13.2.0 h77fa898_8
    - libllvm14 14.0.6 hcd5def8_4
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_8
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - llvm 14.0.6 h32600fe_4
    - llvm-tools 14.0.6 hcd5def8_4
    - llvmdev 14.0.6 hcd5def8_4
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
    - zlib 1.3.1 h4ab18f5_1
  run:
    - libgcc-ng >=12
    - libllvm14 >=14.0.6,<14.1.0a0
    - libstdcxx-ng >=12
    - libzlib >=1.3.1,<2.0a0
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands:
    - python -m llvmlite.tests
  imports:
    - llvmlite
    - llvmlite.binding
about:
  dev_url: https://github.com/numba/llvmlite
  doc_url: http://llvmlite.pydata.org/
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240613.3.1
  recipe-maintainers:
    - jakirkham
    - marcelotrevisani
    - mbargull
    - souravsingh
    - xhochy
  remote_url: https://github.com/conda-forge/llvmlite-feedstock
  sha: 3e1fea77bca4d9911262989e5e7bcfa1608d2cc2
