# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Mar 21 11:35:09 2024
# ------------------------------------------------

package:
  name: libaec
  version: 1.1.3
source:
  patches:
    - 0001-Disable-building-the-static-library.patch
  sha256: 1bafbfaef773bf8f5e5451e6c1f23da36c7199186cc0974fb9874bf723fe4270
  url: https://gitlab.dkrz.de/k202009/libaec/-/archive/v1.1.3/libaec-v1.1.3.tar.gz
build:
  number: '0'
  run_exports:
    - libaec >=1.1.3,<2.0a0
  string: h59595ed_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hdade7a5_3
    - bzip2 1.0.8 hd590300_5
    - c-ares 1.27.0 hd590300_0
    - ca-certificates 2024.2.2 hbcca054_0
    - cmake 3.28.4 hcfe8598_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 he2b93b0_5
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libcurl 8.6.0 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.2 h59595ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 12.3.0 h0f45ef3_5
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_105
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuv 1.48.0 hd590300_0
    - libzlib 1.2.13 hd590300_5
    - make 4.3 hd18ef5c_1
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.12 he073ed8_17
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.5 hfc55251_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libstdcxx-ng 13.2.0 h7e041cc_5
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
test:
  commands:
    - test -f ${PREFIX}/lib/libaec${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsz${SHLIB_EXT}
about:
  description: 'Libaec provides fast lossless compression of 1 up to 32 bit wide signed
    or unsigned integers (samples).

    The library achieves best results for low entropy data as often encountered in
    space imaging instrument

    data or numerical model output from weather or climate simulations. While floating
    point representations

    are not directly supported, they can also be efficiently coded by grouping exponents
    and mantissa.

    Libaec implements Golomb-Rice coding as defined in the Space Data System Standard
    documents 121.0-B-2

    and 120.0-G-2.

    '
  dev_url: https://gitlab.dkrz.de/k202009/libaec
  home: https://gitlab.dkrz.de/k202009/libaec
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Adaptive Entropy Coding library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240321.2.1
  recipe-maintainers:
    - hmaarrfk
    - kmuehlbauer
  remote_url: https://github.com/conda-forge/libaec-feedstock
  sha: 31212ab607da1e7695696e83dd1072dd024e8e4e
