# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: importlib_metadata
  version: 8.0.0
source:
  sha256: 188bd24e4c346d3f0a933f275c2fec67050326a856b9a359881d7c2a697e8812
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-8.0.0.tar.gz
build:
  noarch: generic
  number: 0
  string: hd8ed1ab_0
requirements:
  build: []
  run:
    - importlib-metadata >=8.0.0,<8.0.1.0a0
test:
  imports:
    - importlib_metadata
about:
  home: https://github.com/python/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240625.2.1
  recipe-maintainers:
    - marcelotrevisani
    - nehaljwani
    - nicoddemus
  remote_url: https://github.com/conda-forge/importlib_metadata-feedstock
  sha: 813267e69526570c332d4dea51dfacda016884a9
