# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jun 25 07:29:06 2024
# ------------------------------------------------

package:
  name: pandoc
  version: 3.2.1
source:
  sha256: 3568b0ab38aa8c7ddce0812fa9f7bea8aa43d1657c5e1e816ed92807719c0e2d
  url: https://github.com/jgm/pandoc/releases/download/3.2.1/pandoc-3.2.1-linux-amd64.tar.gz
build:
  missing_dso_whitelist: null
  number: '0'
  string: ha770c72_0
requirements:
  build: []
  run: []
test:
  commands:
    - pandoc --version
    - pandoc --help
about:
  description: 'Pandoc is a Haskell library for converting from one markup format
    to

    another, and a command-line tool that uses this library.

    '
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/blob/master/MANUAL.txt
  doc_url: http://pandoc.org/MANUAL.html
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240625.2.1
  recipe-maintainers:
    - jankatins
    - kiwi0fruit
    - m-rossi
    - ocefpaf
  remote_url: https://github.com/conda-forge/pandoc-feedstock
  sha: 849eebc7ed3a20d7a03de1c7b680892f4afce0a2
