# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Mar 16 11:50:32 2024
# ------------------------------------------------

package:
  name: types-python-dateutil
  version: 2.9.0.20240316
source:
  sha256: 5d2f2e240b86905e40944dd787db6da9263f0deabef1076ddaed797351ec0202
  url: https://pypi.io/packages/source/t/types-python-dateutil/types-python-dateutil-2.9.0.20240316.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/types-python-dateutil_1710589910274/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.6
test:
  commands:
    - test -f $SP_DIR/dateutil-stubs/__init__.pyi
about:
  home: https://github.com/python/typeshed
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  summary: Typing stubs for python-dateutil
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240316.2.1
  recipe-maintainers:
    - conda-forge/mypy
    - fhoehle
  remote_url: https://github.com/conda-forge/types-python-dateutil-feedstock
  sha: a94144bb21e3ff0b5ab0d6d73accfa3a7e877844
