# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Feb  2 15:12:00 2024
# ------------------------------------------------

package:
  name: pytz
  version: '2024.1'
source:
  sha256: 2a29735ea9c18baf14b448846bde5a48030ed267578472d8955cd0e7443a9812
  url: https://pypi.io/packages/source/p/pytz/pytz-2024.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pytz_1706886791323/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - pip 23.3.2 pyhd8ed1ab_0
    - python 3.12.1 hab00c5b_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023d h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
  imports:
    - pytz
  requires:
    - pip
about:
  description: 'pytz brings the Olson tz database into Python. This library allows

    accurate and cross platform timezone calculations using Python 2.4 or

    higher. It also solves the issue of ambiguous times at the end of daylight

    saving time.

    '
  dev_url: https://github.com/newvem/pytz
  doc_url: http://pythonhosted.org/pytz/
  home: http://pythonhosted.org/pytz/
  license: MIT
  license_file: LICENSE.txt
  summary: World timezone definitions, modern and historical.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240202.2.1
  recipe-maintainers:
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/pytz-feedstock
  sha: 25b90fc519c5d59a0d90138b24822da4f8879b4e
