# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jun 21 15:54:11 2024
# ------------------------------------------------

package:
  name: cairo
  version: 1.18.0
source:
  patches:
    - meson-darwin-versions.patch
  sha256: 243a0736b978a33dee29f9cca7521733b78a65b5418206fef7bd1c3d4cf10b64
  url: http://cairographics.org/releases/cairo-1.18.0.tar.xz
build:
  number: '2'
  run_exports:
    - cairo >=1.18.0,<2.0a0
  string: hbb29018_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_8
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - gcc_impl_linux-64 12.3.0 h58ffeeb_11
    - gcc_linux-64 12.3.0 h9528a6a_8
    - gxx_impl_linux-64 12.3.0 h2a574ab_11
    - gxx_linux-64 12.3.0 ha28b414_8
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-devel_linux-64 12.3.0 h6b66f73_111
    - libgcc-ng 13.2.0 h77fa898_11
    - libgomp 13.2.0 h77fa898_11
    - libnsl 2.0.1 hd590300_0
    - libsanitizer 12.3.0 hb8811af_11
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-devel_linux-64 12.3.0 h6b66f73_111
    - libstdcxx-ng 13.2.0 hc0a3c3a_11
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - meson 1.4.1 pyhd8ed1ab_0
    - ncurses 6.5 h59595ed_0
    - ninja 1.12.1 h297d8ca_0
    - openssl 3.3.1 h4ab18f5_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - pthread-stubs 0.4 h36c2ea0_1001
    - python 3.12.4 h194c7f8_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - setuptools 70.1.0 pyhd8ed1ab_0
    - sysroot_linux-64 2.12 he073ed8_17
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xcb-proto 1.17.0 py312h98912ed_0
    - xorg-renderproto 0.11.1 h7f98852_1002
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - expat 2.6.2 h59595ed_0
    - fontconfig 2.14.2 h14ed4e7_0
    - freetype 2.12.1 h267a509_2
    - glib 2.80.2 h8a4344b_1
    - glib-tools 2.80.2 h73ef956_1
    - icu 73.2 h59595ed_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_11
    - libglib 2.80.2 h8a4344b_1
    - libgomp 13.2.0 h77fa898_11
    - libiconv 1.17 hd590300_2
    - libnsl 2.0.1 hd590300_0
    - libpng 1.6.43 h2797004_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_11
    - libuuid 2.38.1 h0b41bf4_0
    - libxcb 1.16 hd590300_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pcre2 10.44 h0f59acf_0
    - pixman 0.43.2 h59595ed_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - python 3.12.4 h194c7f8_0_cpython
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libice 1.1.1 hd590300_0
    - xorg-libsm 1.2.4 h7391055_0
    - xorg-libx11 1.8.9 hb711507_1
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-libxext 1.3.4 h0b41bf4_2
    - xorg-libxrender 0.9.11 hd590300_0
    - xorg-renderproto 0.11.1 h7f98852_1002
    - xorg-xextproto 7.3.0 h0b41bf4_1003
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
    - zlib 1.3.1 h4ab18f5_1
  run:
    - fontconfig >=2.14.2,<3.0a0
    - fonts-conda-ecosystem
    - freetype >=2.12.1,<3.0a0
    - icu >=73.2,<74.0a0
    - libgcc-ng >=12
    - libglib >=2.80.2,<3.0a0
    - libpng >=1.6.43,<1.7.0a0
    - libstdcxx-ng >=12
    - libxcb >=1.16,<1.17.0a0
    - libzlib >=1.3.1,<2.0a0
    - pixman >=0.43.2,<1.0a0
    - xorg-libice >=1.1.1,<2.0a0
    - xorg-libsm >=1.2.4,<2.0a0
    - xorg-libx11 >=1.8.9,<2.0a0
    - xorg-libxext >=1.3.4,<2.0a0
    - xorg-libxrender >=0.9.11,<0.10.0a0
    - zlib
test:
  commands:
    - cairo-trace --help
    - test -f $PREFIX/lib/libcairo.a
    - test -f $PREFIX/lib/libcairo.so
    - test -f $PREFIX/lib/libcairo-gobject.a
    - test -f $PREFIX/lib/libcairo-gobject.so
    - test -f $PREFIX/lib/libcairo-script-interpreter.a
    - test -f $PREFIX/lib/libcairo-script-interpreter.so
    - test -f $PREFIX/lib/pkgconfig/cairo-xlib.pc
    - test -f $PREFIX/include/cairo/cairo.h
    - grep -q "CAIRO_HAS_FC_FONT 1" $PREFIX/include/cairo/cairo-features.h
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags cairo
    - pkg-config --cflags cairo-fc
    - pkg-config --cflags cairo-gobject
  requires:
    - glib
    - pkg-config
about:
  dev_url: https://gitlab.freedesktop.org/cairo/cairo
  doc_url: https://www.cairographics.org/documentation/
  home: http://cairographics.org/
  license: LGPL-2.1-only or MPL-1.1
  license_file:
    - COPYING
    - COPYING-LGPL-2.1
    - COPYING-MPL-1.1
  summary: Cairo is a 2D graphics library with support for multiple output devices.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240621.3.1
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
    - tschoonj
  remote_url: https://github.com/conda-forge/cairo-feedstock
  sha: ac1ea43dd4e609affe087c4f0e384c77ca934cdf
