# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Aug 23 19:17:13 2023
# ------------------------------------------------

package:
  name: argon2-cffi
  version: 23.1.0
source:
  sha256: 879c3e79a2729ce768ebb7d36d4609e3a78a4ca2ec3a9f12286ca057e3d0db08
  url: https://pypi.io/packages/source/a/argon2-cffi/argon2_cffi-23.1.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/argon2-cffi_1692818318753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - editables 0.3 pyhd8ed1ab_0
    - hatch-fancy-pypi-readme 23.1.0 pyhd8ed1ab_0
    - hatch-vcs 0.3.0 pyhd8ed1ab_0
    - hatchling 1.18.0 pyhd8ed1ab_0
    - importlib-metadata 6.8.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.42.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - packaging 23.1 pyhd8ed1ab_0
    - pathspec 0.11.2 pyhd8ed1ab_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pluggy 1.2.0 pyhd8ed1ab_0
    - python 3.11.4 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.1.2 pyhd8ed1ab_0
    - setuptools-scm 7.1.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2023.8.7 pyhd8ed1ab_0
    - typing-extensions 4.7.1 hd8ed1ab_0
    - typing_extensions 4.7.1 pyha770c72_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.16.2 pyhd8ed1ab_0
  run:
    - argon2-cffi-bindings
    - python >=3.7
    - typing-extensions
  run_constrained:
    - argon2_cffi ==999
test:
  commands:
    - pip check
  imports:
    - argon2
  requires:
    - pip
about:
  description: 'Argon2 won the Password Hashing Competition and argon2_cffi is the
    simplest

    way to use it in Python and PyPy

    '
  dev_url: https://github.com/hynek/argon2_cffi/
  doc_url: https://argon2-cffi.readthedocs.io/en/stable/
  home: https://argon2-cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The secure Argon2 password hashing algorithm.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - stuertz
