# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Feb  9 02:05:28 2024
# ------------------------------------------------

package:
  name: debugpy
  version: 1.8.1
source:
  sha256: f696d6be15be87aef621917585f9bb94b1dc9e8aced570db1b8a6fc14e8f9b42
  url: https://pypi.io/packages/source/d/debugpy/debugpy-1.8.1.zip
build:
  number: '0'
  string: py310hc6cd4ac_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h76fc315_2
    - gxx_impl_linux-64 12.3.0 he2b93b0_5
    - gxx_linux-64 12.3.0 h8a814eb_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsanitizer 12.3.0 h0f45ef3_5
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_105
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.10.13 hd12c33a_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pip check
  imports:
    - debugpy
    - debugpy.adapter
    - debugpy.common
    - debugpy.launcher
    - debugpy.server
  requires:
    - pip
about:
  dev_url: https://github.com/microsoft/debugpy
  home: https://github.com/Microsoft/debugpy
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyNotices.txt
  summary: An implementation of the Debug Adapter Protocol for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240208.2.1
  recipe-maintainers:
    - jtilly
    - xhochy
  remote_url: https://github.com/conda-forge/debugpy-feedstock
  sha: c6334fd2f1174c9fd969719ee2ab2b48c622105a
