# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Jan 22 14:30:25 2024
# ------------------------------------------------

package:
  name: ipykernel
  version: 6.28.0
source:
  patches:
    - patches/0001-test-conf.patch
  sha256: 69c11403d26de69df02225916f916b37ea4b9af417da0a8c827f84328d88e5f3
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-6.28.0.tar.gz
build:
  number: '0'
  script:
    - /croot/ipykernel_1705933831282/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
      -m pip install . --no-deps --no-build-isolation -vv
    - /croot/ipykernel_1705933831282/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
      -m ipykernel install --sys-prefix
  string: py312h06a4308_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - patch 2.7.6 h7b6447c_1001
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - asttokens 2.0.5 pyhd3eb1b0_0
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.12.12 h06a4308_0
    - comm 0.1.2 py312h06a4308_0
    - decorator 5.1.1 pyhd3eb1b0_0
    - editables 0.3 py312h06a4308_0
    - executing 0.8.3 pyhd3eb1b0_0
    - expat 2.5.0 h6a678d5_0
    - hatchling 1.18.0 py312h06a4308_1
    - ipython 8.20.0 py312h06a4308_0
    - jedi 0.18.1 py312h06a4308_1
    - jupyter_client 8.6.0 py312h06a4308_0
    - jupyter_core 5.5.0 py312h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libsodium 1.0.18 h7b6447c_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - matplotlib-inline 0.1.6 py312h06a4308_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.12 h7f8727e_0
    - packaging 23.1 py312h06a4308_0
    - parso 0.8.3 pyhd3eb1b0_0
    - pathspec 0.10.3 py312h06a4308_0
    - pexpect 4.8.0 pyhd3eb1b0_3
    - pip 23.3.1 py312h06a4308_0
    - platformdirs 3.10.0 py312h06a4308_0
    - pluggy 1.0.0 py312h06a4308_1
    - prompt-toolkit 3.0.43 py312h06a4308_0
    - prompt_toolkit 3.0.43 hd3eb1b0_0
    - psutil 5.9.0 py312h5eee18b_0
    - ptyprocess 0.7.0 pyhd3eb1b0_2
    - pure_eval 0.2.2 pyhd3eb1b0_0
    - pygments 2.15.1 py312h06a4308_1
    - python 3.12.1 h996f2a0_0
    - python-dateutil 2.8.2 pyhd3eb1b0_0
    - pyzmq 25.1.2 py312h6a678d5_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.2.2 py312h06a4308_0
    - six 1.16.0 pyhd3eb1b0_1
    - sqlite 3.41.2 h5eee18b_0
    - stack_data 0.2.0 pyhd3eb1b0_0
    - tk 8.6.12 h1ccaba5_0
    - tornado 6.3.3 py312h5eee18b_0
    - traitlets 5.7.1 py312h06a4308_0
    - trove-classifiers 2023.10.18 py312h06a4308_0
    - tzdata 2023d h04d1e81_0
    - wcwidth 0.2.5 pyhd3eb1b0_0
    - wheel 0.41.2 py312h06a4308_0
    - xz 5.4.5 h5eee18b_0
    - zeromq 4.3.5 h6a678d5_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - comm >=0.1.1
    - debugpy >=1.6.5
    - ipython >=7.23.1
    - jupyter_client >=6.1.12
    - jupyter_core >=4.12,!=5.0.*
    - matplotlib-inline >=0.1
    - nest-asyncio
    - packaging
    - psutil
    - python >=3.12,<3.13.0a0
    - pyzmq >=24
    - tornado >=6.1
    - traitlets >=5.4.0
test:
  commands:
    - pip check
  requires:
    - pip
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'A powerful interactive Python shell and a Jupyter kernel to work with

    Python code in Jupyter notebooks and other interactive frontends.

    '
  dev_url: https://github.com/ipython/ipykernel
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IPython Kernel for Jupyter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 32929f4e-fd6f-4c73-9f59-eaaea1990899
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/ipykernel-feedstock.git
  sha: f2be91074eefb884bde3eaf5ea94fb09cd18718c
