CI: azure
c_compiler: gcc
c_compiler_version: '12'
c_stdlib: sysroot
c_stdlib_version: '2.12'
cdt_name: cos6
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fortran_compiler: gfortran
freetype: '2'
ignore_build_only_deps:
- numpy
- python
lcms2: '2'
libjpeg_turbo: '3'
libtiff: '4.6'
libwebp: '1'
libxcb: '1.15'
lua: '5'
numpy: '1.22'
openjpeg: '2'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: 3.10.* *_cpython
python_impl: cpython
r_base: '3.5'
target_platform: linux-64
tk: '8.6'
zip_keys:
- - c_stdlib_version
  - cdt_name
- - python
  - python_impl
zlib: '1.2'
