# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Feb 22 03:31:01 2023
# ------------------------------------------------

package:
  name: xorg-libxext
  version: 1.3.4
source:
  sha256: 59ad6fcce98deaecc14d39a672cf218ca37aba617c9a0f691cac3bcd28edf82b
  url: https://www.x.org/releases/individual/lib/libXext-1.3.4.tar.bz2
build:
  detect_binary_files_with_prefix: true
  number: '2'
  run_exports:
    - xorg-libxext >=1.3.4,<2.0a0
  string: h0b41bf4_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_linux-64 2.39 h5fc0e48_11
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_linux-64 11.3.0 he6f903b_11
    - gettext 0.21.1 h27087fc_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 11.3.0 h239ccf8_19
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libtool 2.4.7 h27087fc_0
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 2_h7f98852_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_15
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libxcb 1.13 h7f98852_1004
    - pthread-stubs 0.4 h36c2ea0_1001
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libx11 1.7.2 h7f98852_0
    - xorg-libxau 1.0.9 h7f98852_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-util-macros 1.19.3 h7f98852_0
    - xorg-xextproto 7.3.0 h7f98852_1002
    - xorg-xproto 7.0.31 h7f98852_1007
  run:
    - libgcc-ng >=12
    - xorg-libx11 >=1.7.2,<2.0a0
    - xorg-xextproto
test:
  commands:
    - test -f $PREFIX/lib/libXext.so
about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org extensions library.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - pkgw
