# This file created by conda-build 24.5.0
# ------------------------------------------------

package:
  name: matplotlib-base
  version: 3.8.4
source:
  sha256: 7c4f370b7550eec8342c102f9dd80da3bec2895d7f514f5f6378764db4cb0e35
  url: https://github.com/matplotlib/matplotlib/archive/v3.8.4.tar.gz
build:
  ignore_run_exports_from:
    - zlib
  number: 2
  string: py310hef631a5_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha885e6a_0
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 h58ffeeb_7
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 h2a574ab_7
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h55db66e_0
    - libgcc-devel_linux-64 12.3.0 h0223996_107
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libsanitizer 12.3.0 hb8811af_7
    - libstdcxx-devel_linux-64 12.3.0 h0223996_107
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libtool 2.4.7 h27087fc_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _numpy_rc 1 h23db71c_0
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - certifi 2024.2.2 pyhd8ed1ab_0
    - freetype 2.12.1 h267a509_2
    - ld_impl_linux-64 2.40 h55db66e_0
    - libblas 3.9.0 22_linux64_openblas
    - libcblas 3.9.0 22_linux64_openblas
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgfortran-ng 13.2.0 h69a702a_7
    - libgfortran5 13.2.0 hca663fb_7
    - libgomp 13.2.0 h77fa898_7
    - liblapack 3.9.0 22_linux64_openblas
    - libnsl 2.0.1 hd590300_0
    - libopenblas 0.3.27 pthreads_h413a1c8_0
    - libpng 1.6.43 h2797004_0
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.5 h59595ed_0
    - numpy 2.0.0rc2 py310h515e003_0
    - openssl 3.3.0 hd590300_0
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pybind11 2.12.0 py310hd41b1e2_0
    - pybind11-global 2.12.0 py310hd41b1e2_0
    - python 3.10.14 hd12c33a_0_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - setuptools_scm 8.1.0 hd8ed1ab_0
    - setuptools_scm_git_archive 1.4.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.11.0 hd8ed1ab_0
    - typing_extensions 4.11.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
  run:
    - certifi >=2020.06.20
    - contourpy >=1.0.1
    - cycler >=0.10
    - fonttools >=4.22.0
    - freetype >=2.12.1,<3.0a0
    - kiwisolver >=1.3.1
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - numpy >=1.19,<3
    - numpy >=1.21
    - packaging >=20.0
    - pillow >=8
    - pyparsing >=2.3.1
    - python >=3.10,<3.11.0a0
    - python-dateutil >=2.7
    - python_abi 3.10.* *_cp310
    - tk >=8.6.13,<8.7.0a0
test:
  imports:
    - matplotlib
    - matplotlib._image
    - matplotlib._path
    - matplotlib._qhull
    - matplotlib._tri
    - matplotlib._ttconv
    - matplotlib.backends._backend_agg
    - matplotlib.backends._tkagg
    - matplotlib.ft2font
    - matplotlib.pyplot
    - mpl_toolkits
    - pylab
about:
  description: 'matplotlib is a python 2D plotting library which produces publication

    quality figures in a variety of hardcopy formats and interactive

    environments across platforms. matplotlib can be used in Python scripts,

    the Python and IPython shell (ala MATLAB or Mathematica), web

    application servers, and six graphical user interface toolkits.

    '
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html
  home: http://matplotlib.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE/LICENSE
  license_url: http://matplotlib.sourceforge.net/users/license.html
  summary: Publication quality figures in Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240517.3.1
  recipe-maintainers:
    - dopplershift
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
  remote_url: https://github.com/conda-forge/matplotlib-feedstock
  sha: de2087562355a9cb97ff864ac64ba82fe7d7b7d2
