# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jun 15 18:42:34 2024
# ------------------------------------------------

package:
  name: python-fastjsonschema
  version: 2.20.0
source:
  - folder: dist
    sha256: 3d48fc5300ee96f5d116f10fe6f28d938e6008f59a6a025c2649475b87f76a23
    url: https://pypi.io/packages/source/f/fastjsonschema/fastjsonschema-2.20.0.tar.gz
  - folder: src
    sha256: 2d2e4951614ee57a08f7bdb689687d4f31e59e3ad466c085495105a72ad95b38
    url: https://github.com/horejsek/python-fastjsonschema/archive/v2.20.0.tar.gz
build:
  noarch: python
  number: '0'
  script: cd dist && /home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1718477020893/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_4
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_9
    - libgomp 13.2.0 h77fa898_9
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.3
test:
  commands:
    - cd src && cd tests && pytest -vv --cov fastjsonschema -k "not (compile_to_code_ipv6_regex
      or compile_to_code_custom_format_with_refs)" --cov-report term-missing:skip-covered
      --no-cov-on-fail --cov-fail-under 84
  imports:
    - fastjsonschema
  requires:
    - pytest-benchmark
    - pytest-cov
  source_files:
    - src/tests
about:
  description: 'fastjsonschema implements validation of JSON documents by JSON schema.
    The

    library implements JSON schema drafts 04, 06 and 07. The main purpose is to

    have a really fast implementation.

    '
  doc_source_url: https://github.com/horejsek/python-fastjsonschema/tree/master/docs
  doc_url: https://horejsek.github.io/python-fastjsonschema
  home: https://github.com/horejsek/python-fastjsonschema
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Fastest Python implementation of JSON schema
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240615.2.1
  recipe-maintainers:
    - bollwyvl
  remote_url: https://github.com/conda-forge/python-fastjsonschema-feedstock
  sha: 985b43fba43497d3e9bc8a6c05cb967fe1640e6b
