# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon May 27 12:14:49 2024
# ------------------------------------------------

package:
  name: numexpr
  version: 2.10.0
source:
  sha256: c89e930752639df040539160326d8f99a84159bbea41943ab8e960591edaaef0
  url: https://pypi.io/packages/source/n/numexpr/numexpr-2.10.0.tar.gz
build:
  number: '100'
  script: bash /home/conda/recipe_root/build_without_mkl.sh
  string: py312hf412c99_100
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_1
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 h58ffeeb_7
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 h2a574ab_7
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_1
    - libgcc-devel_linux-64 12.3.0 h0223996_107
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libsanitizer 12.3.0 hb8811af_7
    - libstdcxx-devel_linux-64 12.3.0 h0223996_107
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _numpy_rc 1 h23db71c_0
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_1
    - libblas 3.9.0 22_linux64_openblas
    - libcblas 3.9.0 22_linux64_openblas
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgfortran-ng 13.2.0 h69a702a_7
    - libgfortran5 13.2.0 hca663fb_7
    - libgomp 13.2.0 h77fa898_7
    - liblapack 3.9.0 22_linux64_openblas
    - libnsl 2.0.1 hd590300_0
    - libopenblas 0.3.27 pthreads_h413a1c8_0
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.5 h59595ed_0
    - numpy 2.0.0rc2 py312h22e1c76_0
    - openssl 3.3.0 h4ab18f5_3
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - nomkl
    - numpy >=1.19,<3
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  imports:
    - numexpr
    - numexpr.interpreter
about:
  description: 'Numexpr is a fast numerical expression evaluator for NumPy. With it,

    expressions that operate on arrays (like "3*a+4*b") are accelerated and use

    less memory than doing the same calculation in Python.

    '
  dev_url: https://github.com/pydata/numexpr
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  home: https://github.com/pydata/numexpr
  license: MIT
  license_file: LICENSE.txt
  summary: Fast numerical expression evaluator for NumPy.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240527.1.1
  recipe-maintainers:
    - djkirkham
    - msarahan
    - ocefpaf
    - scopatz
  remote_url: https://github.com/conda-forge/numexpr-feedstock
  sha: d2820571782be1a9756f6e3cd68adee28ba8d140
