# This file created by conda-build 3.28.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jan 10 21:19:46 2024
# ------------------------------------------------

package:
  name: sphinxcontrib-bibtex
  version: 2.6.2
source:
  fn: sphinxcontrib-bibtex-2.6.2.tar.gz
  sha256: f487af694336f28bfb7d6a17070953a7d264bec43000a2379724274f5f8d70ae
  url: https://pypi.io/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-2.6.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/sphinxcontrib-bibtex_1704921668642/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - alabaster 0.7.16 pyhd8ed1ab_0
    - babel 2.14.0 pyhd8ed1ab_0
    - brotli-python 1.1.0 py312h30efb56_1
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - certifi 2023.11.17 pyhd8ed1ab_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - dataclasses 0.8 pyhc8e2a94_3
    - docutils 0.20.1 py312h7900ff3_3
    - idna 3.6 pyhd8ed1ab_0
    - imagesize 1.4.1 pyhd8ed1ab_0
    - importlib-metadata 7.0.1 pyha770c72_0
    - importlib_metadata 7.0.1 hd8ed1ab_0
    - jinja2 3.1.2 pyhd8ed1ab_1
    - latexcodec 2.0.1 pyh9f0ad1d_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - markupsafe 2.1.3 py312h98912ed_1
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - packaging 23.2 pyhd8ed1ab_0
    - pip 23.3.2 pyhd8ed1ab_0
    - pybtex 0.24.0 pyhd8ed1ab_2
    - pybtex-docutils 1.0.3 py312h7900ff3_1
    - pygments 2.17.2 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.12.1 hab00c5b_1_cpython
    - python_abi 3.12 4_cp312
    - pytz 2023.3.post1 pyhd8ed1ab_0
    - pyyaml 6.0.1 py312h98912ed_1
    - readline 8.2 h8228510_1
    - requests 2.31.0 pyhd8ed1ab_0
    - setuptools 69.0.3 pyhd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - snowballstemmer 2.2.0 pyhd8ed1ab_0
    - sphinx 7.2.6 pyhd8ed1ab_0
    - sphinxcontrib-applehelp 1.0.7 pyhd8ed1ab_0
    - sphinxcontrib-devhelp 1.0.5 pyhd8ed1ab_0
    - sphinxcontrib-htmlhelp 2.0.4 pyhd8ed1ab_0
    - sphinxcontrib-jsmath 1.0.1 pyhd8ed1ab_0
    - sphinxcontrib-qthelp 1.0.6 pyhd8ed1ab_0
    - sphinxcontrib-serializinghtml 1.1.9 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023d h0c530f3_0
    - urllib3 2.1.0 pyhd8ed1ab_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - yaml 0.2.5 h7f98852_2
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - dataclasses
    - docutils >=0.8,!=0.18.*,!=0.19.*
    - importlib_metadata >=3.6
    - pybtex >=0.24
    - pybtex-docutils >=1.0.0
    - python >=3.7
    - sphinx >=3.5
test:
  commands:
    - pip check
  imports:
    - sphinxcontrib
    - sphinxcontrib.bibtex
  requires:
    - pip
about:
  description: This extension allows BibTeX citations to be inserted into documentation
    generated by Sphinx."
  dev_url: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/
  doc_url: http://sphinxcontrib-bibtex.readthedocs.org/en/latest/
  home: https://github.com/mcmtroffaes/sphinxcontrib-bibtex
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Sphinx extension for BibTeX style citations.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240110.2.1
  recipe-maintainers:
    - conda-forge/sphinx
    - croth1
  remote_url: https://github.com/conda-forge/sphinxcontrib-bibtex-feedstock
  sha: 3f4c6a78a19cb8577d4818a15fd3e9c453c8563e
