# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jun  6 09:47:03 2024
# ------------------------------------------------

package:
  name: webcolors
  version: 24.6.0
source:
  fn: webcolors-24.6.0.tar.gz
  sha256: 1d160d1de46b3e81e58d0a280d0c78b467dc80f47294b91b1ad8029d2cedb55b
  url: https://pypi.io/packages/source/w/webcolors/webcolors-24.6.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/webcolors_1717667289718/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_2
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.5
test:
  imports:
    - webcolors
about:
  home: https://github.com/ubernostrum/webcolors
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Library for working with HTML/CSS color formats in Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240606.2.1
  recipe-maintainers:
    - jakirkham
  remote_url: https://github.com/conda-forge/webcolors-feedstock
  sha: 2fd07f18064d64eaa7d56888afb5d3ad23864209
