# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 26 08:53:14 2022
# ------------------------------------------------

package:
  name: py-cpuinfo
  version: 9.0.0
source:
  fn: py-cpuinfo-9.0.0.tar.gz
  sha256: 3cdbbf3fac90dc6f118bfd64384f309edeadd902d7c8fb17f02ffa1fc3f49690
  url: https://pypi.io/packages/source/p/py-cpuinfo/py-cpuinfo-9.0.0.tar.gz
build:
  entry_points:
    - cpuinfo = cpuinfo:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/py-cpuinfo_1666774466606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - ld_impl_linux-64 2.39 hc81fddc_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.39.4 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.5 h166bdaf_2
    - pip 22.3 pyhd8ed1ab_0
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.5.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022e h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - cpuinfo
  imports:
    - cpuinfo
about:
  dev_url: https://github.com/workhorsy/py-cpuinfo
  home: https://github.com/workhorsy/py-cpuinfo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A module for getting CPU info with pure Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mstimberg
