# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jun 25 00:15:02 2024
# ------------------------------------------------

package:
  name: psutil
  version: 6.0.0
source:
  sha256: 8faae4f310b6d969fa26ca0545338b21f73c6b15db7c4a8d934a5482faa818f2
  url: https://pypi.io/packages/source/p/psutil/psutil-6.0.0.tar.gz
build:
  number: '0'
  script:
    - /home/conda/feedstock_root/build_artifacts/psutil_1719274590885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m pip install --ignore-installed --no-deps .
  string: py312h9a8786e_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_9
    - gcc_impl_linux-64 12.3.0 h58ffeeb_13
    - gcc_linux-64 12.3.0 h9528a6a_9
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.3.0 h6b66f73_113
    - libgcc-ng 13.2.0 h77fa898_13
    - libgomp 13.2.0 h77fa898_13
    - libsanitizer 12.3.0 hb8811af_13
    - libstdcxx-ng 13.2.0 hc0a3c3a_13
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_13
    - libgomp 13.2.0 h77fa898_13
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.4 h194c7f8_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  imports:
    - psutil
    - psutil._psutil_linux
    - psutil._psutil_posix
    - psutil.tests
about:
  description: 'psutil (process and system utilities) is a cross-platform library
    for

    retrieving information on running processes and system utilization (CPU,

    memory, disks, network) in Python. It is useful mainly for system

    monitoring, profiling and limiting process resources and management of

    running processes.

    '
  dev_url: https://github.com/giampaolo/psutil
  doc_source_url: https://github.com/giampaolo/psutil/blob/master/docs/index.rst
  doc_url: http://pythonhosted.org/psutil/
  home: https://github.com/giampaolo/psutil
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A cross-platform process and system utilities module for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240624.3.1
  recipe-maintainers:
    - gqmelo
    - jakirkham
    - nehaljwani
    - pelson
  remote_url: https://github.com/conda-forge/psutil-feedstock
  sha: ebe097f2a29571ce8074d3ebe8e4e1fa89cefa71
