# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun May 19 15:51:03 2024
# ------------------------------------------------

package:
  name: graphviz
  version: 11.0.0
source:
  - patches:
      - patches/0001-Always-link-to-getopt-on-Windows.patch
      - patches/0002-Remove-requirement-of-hard-coded-DLLs-in-PATH.patch
      - patches/0003-Use-WebP-CMake-targets-instead-of-PkgConfig.patch
      - patches/0004-Fix-dependencies-for-gvplugin_gd.patch
    sha256: d374f7d98a1ae985510a82dddd887e8058aa37e5f95b4ce0aa58416d2b22714b
    url: https://gitlab.com/graphviz/graphviz/-/archive/11.0.0/graphviz-11.0.0.tar.gz
  - folder: ltdl_compat
    sha256: a3cf376bca2965634ba05926d4065a46331e71c487d84a4c6aceb795e9458bfd
    url: https://gitlab.com/graphviz/graphviz-windows-dependencies/-/raw/c7eafb3c/x64/include/ltdl.h
build:
  number: '0'
  run_exports:
    - graphviz >=11.0.0,<12.0a0
  string: hc68bbd7_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 ha885e6a_0
    - binutils_linux-64 2.40 hdade7a5_3
    - bison 3.8.2 h59595ed_0
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - flex 2.6.4 h58526e2_1004
    - gcc_impl_linux-64 12.3.0 h58ffeeb_7
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 h2a574ab_7
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-devel_linux-64 12.3.0 h0223996_107
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsanitizer 12.3.0 hb8811af_7
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-devel_linux-64 12.3.0 h0223996_107
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libtool 2.4.7 h27087fc_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.0 hd590300_0
    - perl 5.32.1 7_hd590300_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - sysroot_linux-64 2.12 he073ed8_17
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - atk-1.0 2.38.0 h04ea711_2
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - cairo 1.18.0 h3faef2a_0
    - expat 2.6.2 h59595ed_0
    - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
    - font-ttf-inconsolata 3.000 h77eed37_0
    - font-ttf-source-code-pro 2.038 h77eed37_0
    - font-ttf-ubuntu 0.83 h77eed37_2
    - fontconfig 2.14.2 h14ed4e7_0
    - fonts-conda-ecosystem 1 0
    - fonts-conda-forge 1 0
    - freetype 2.12.1 h267a509_2
    - fribidi 1.0.10 h36c2ea0_0
    - gdk-pixbuf 2.42.12 hb9ae30d_0
    - giflib 5.2.2 hd590300_0
    - glib 2.80.2 hf974151_0
    - glib-tools 2.80.2 hb6ce0ca_0
    - graphite2 1.3.13 h59595ed_1003
    - gtk2 2.24.33 h280cfa0_4
    - gts 0.7.6 h977cf35_4
    - harfbuzz 8.5.0 hfac3d4d_0
    - icu 73.2 h59595ed_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - lerc 4.0.0 h27087fc_0
    - libdeflate 1.20 hd590300_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgd 2.3.3 h119a65a_9
    - libglib 2.80.2 hf974151_0
    - libgomp 13.2.0 h77fa898_7
    - libiconv 1.17 hd590300_2
    - libjpeg-turbo 3.0.0 hd590300_1
    - libnsl 2.0.1 hd590300_0
    - libpng 1.6.43 h2797004_0
    - librsvg 2.58.0 hadf69e7_1
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libtiff 4.6.0 h1dd3fc0_3
    - libuuid 2.38.1 h0b41bf4_0
    - libwebp 1.4.0 h2c329e2_0
    - libwebp-base 1.4.0 hd590300_0
    - libxcb 1.15 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libxml2 2.12.7 hc051c1a_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.0 hd590300_0
    - pango 1.50.14 ha41ecd1_2
    - pcre2 10.43 hcad00b1_0
    - pixman 0.43.2 h59595ed_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libice 1.1.1 hd590300_0
    - xorg-libsm 1.2.4 h7391055_0
    - xorg-libx11 1.8.9 h8ee46fc_0
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-libxext 1.3.4 h0b41bf4_2
    - xorg-libxrender 0.9.11 hd590300_0
    - xorg-renderproto 0.11.1 h7f98852_1002
    - xorg-xextproto 7.3.0 h0b41bf4_1003
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
    - zstd 1.5.6 ha6fb4c9_0
  run:
    - cairo >=1.18.0,<2.0a0
    - fonts-conda-ecosystem
    - gdk-pixbuf >=2.42.12,<3.0a0
    - gtk2
    - gts >=0.7.6,<0.8.0a0
    - libexpat >=2.6.2,<3.0a0
    - libgcc-ng >=12
    - libgd >=2.3.3,<2.4.0a0
    - libglib >=2.80.2,<3.0a0
    - librsvg >=2.58.0,<3.0a0
    - libstdcxx-ng >=12
    - libwebp-base >=1.4.0,<2.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - pango >=1.50.14,<2.0a0
test:
  files:
    - sample.dot
about:
  description: 'Graphviz is an open source graph visualization software. Graph visualization

    is a way of representing structural information as diagrams of abstract

    graphs and networks.

    '
  dev_url: https://gitlab.com/graphviz/graphviz/
  doc_url: https://graphviz.gitlab.io/documentation/
  home: http://www.graphviz.org/
  license: EPL-1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240519.10.1
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - johanneskoester
    - nehaljwani
    - ocefpaf
  remote_url: https://github.com/conda-forge/graphviz-feedstock
  sha: 3a802720dcf9b18b2a8b33b5f96a6d62f5cf71f3
