# This file created by conda-build 3.28.4
# ------------------------------------------------

package:
  name: pcre2
  version: '10.43'
source:
  sha256: f0048e26b02bdfaf43b8cec75030a9c2fe28552bf5caa693d3ccbf4d886fa930
  url: https://github.com/PCRE2Project/pcre2/archive/refs/tags/pcre2-10.43.tar.gz
build:
  number: 0
  run_exports:
    - pcre2 >=10.43,<10.44.0a0
  string: hcad00b1_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - bzip2 1.0.8 hd590300_5
    - c-ares 1.26.0 hd590300_0
    - ca-certificates 2024.2.2 hbcca054_0
    - cmake 3.28.3 hcfe8598_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libcurl 8.5.0 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.5.0 hcb278e6_1
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 12.3.0 h0f45ef3_5
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuv 1.47.0 hd590300_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - ninja 1.11.1 h924138e_0
    - openssl 3.2.1 hd590300_0
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.12 he073ed8_17
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.5 hfc55251_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libzlib 1.2.13 hd590300_5
    - zlib 1.2.13 hd590300_5
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libgcc-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - pcre2test --version
    - pcre2grep --version
    - pcre2-config --version
    - test -f ${PREFIX}/include/pcre2.h
    - test -f ${PREFIX}/include/pcre2posix.h
    - test -f ${PREFIX}/lib/libpcre2-posix${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-posix${SHLIB_EXT}.3
    - test -f ${PREFIX}/lib/libpcre2-posix${SHLIB_EXT}.3.0.5
    - test -f ${PREFIX}/lib/libpcre2-8${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-8${SHLIB_EXT}.0
    - test -f ${PREFIX}/lib/libpcre2-8${SHLIB_EXT}.0.12.0
    - test -f ${PREFIX}/lib/libpcre2-16${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-16${SHLIB_EXT}.0
    - test -f ${PREFIX}/lib/libpcre2-16${SHLIB_EXT}.0.12.0
    - test -f ${PREFIX}/lib/libpcre2-32${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-32${SHLIB_EXT}.0
    - test -f ${PREFIX}/lib/libpcre2-32${SHLIB_EXT}.0.12.0
    - test -f ${PREFIX}/lib/pkgconfig/libpcre2-8.pc
    - test -f ${PREFIX}/lib/pkgconfig/libpcre2-16.pc
    - test -f ${PREFIX}/lib/pkgconfig/libpcre2-32.pc
    - test -f ${PREFIX}/lib/pkgconfig/libpcre2-posix.pc
    - test -f ${PREFIX}/cmake/pcre2-config.cmake
    - test -f ${PREFIX}/cmake/pcre2-config-version.cmake
about:
  description: 'The PCRE library is a set of functions that implement regular expression
    pattern matching

    using the same syntax and semantics as Perl 5. PCRE has its own native API, as
    well as a set of

    wrapper functions that correspond to the POSIX regular expression API. The PCRE
    library is

    free, even for building proprietary software.

    '
  doc_url: http://www.pcre.org/current/doc/html/
  home: http://www.pcre.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE
  summary: Regular expression pattern matching using Perl 5 syntax and semantics.
extra:
  copy_test_source_files: true
  feedstock-name: pcre2
  final: true
  flow_run_id: azure_20240216.3.1
  recipe-maintainers:
    - dfornika
    - mariusvniekerk
    - xhochy
  remote_url: https://github.com/conda-forge/pcre2-feedstock
  sha: 3b2b56e3d07ffdd6d13058fe67e8fd52f0b9839b
