# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: ld_impl_linux-64
  version: '2.40'
source:
  - patches:
      - patches/0001-fallback-sysroot.diff
      - patches/bug30079.patch
    sha256: f8298eb153a4b37d112e945aa5cb2850040bcf26a3ea65b5a715c83afe05e48a
    url: https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.bz2
build:
  detect_binary_files_with_prefix: false
  ignore_run_exports_from:
    - gcc_bootstrap_linux-64 12.*
  merge_build_host: false
  number: 7
  string: hf3520f5_7
requirements:
  build:
    - gcc_bootstrap_linux-64 12.3.0 hca58faa_7
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - sysroot_linux-64 2.12 he073ed8_17
  run: []
  run_constrained:
    - binutils_impl_linux-64 2.40
test:
  commands:
    - x86_64-conda-linux-gnu-ld --help
    - echo "conda_cos6"
about:
  home: https://www.gnu.org/software/binutils/
  license: GPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LIB
    - COPYING3
    - COPYING3.LIB
  summary: 'A set of programming tools for creating and managing binary programs,
    object files,

    libraries, profile data, and assembly source code.

    '
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240617.2.1
  recipe-maintainers:
    - beckermr
    - frol
    - isuruf
    - jjhelmus
  remote_url: https://github.com/conda-forge/binutils-feedstock
  sha: 5d6e9140fa68c9ab83d2284bba4d8d4332e52d0c
