# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: atk-1.0
  version: 2.38.0
source:
  sha256: ac4de2a4ef4bd5665052952fe169657e65e895c5057dffb3c2a810f6191a0c36
  url: http://ftp.gnome.org/pub/gnome/sources/atk/2.38/atk-2.38.0.tar.xz
build:
  number: 2
  run_exports:
    - atk-1.0 >=2.38.0
  string: h04ea711_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha885e6a_0
    - binutils_linux-64 2.40 hdade7a5_3
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - cairo 1.18.0 h3faef2a_0
    - expat 2.6.2 h59595ed_0
    - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
    - font-ttf-inconsolata 3.000 h77eed37_0
    - font-ttf-source-code-pro 2.038 h77eed37_0
    - font-ttf-ubuntu 0.83 h77eed37_1
    - fontconfig 2.14.2 h14ed4e7_0
    - fonts-conda-ecosystem 1 0
    - fonts-conda-forge 1 0
    - freetype 2.12.1 h267a509_2
    - g-ir-build-tools 1.80.1 py312hcb69f48_0
    - g-ir-host-tools 1.80.1 hfff48b1_0
    - gcc_impl_linux-64 12.3.0 h1562d66_6
    - gcc_linux-64 12.3.0 h6477408_3
    - gobject-introspection 1.80.1 py312h15a1d3f_0
    - gxx_impl_linux-64 12.3.0 h1562d66_6
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - icu 73.2 h59595ed_0
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-devel_linux-64 12.3.0 h2af2641_106
    - libgcc-ng 13.2.0 hc881cc4_6
    - libgirepository 1.80.1 h003a4f0_0
    - libglib 2.80.0 hf2295e7_6
    - libgomp 13.2.0 hc881cc4_6
    - libiconv 1.17 hd590300_2
    - libnsl 2.0.1 hd590300_0
    - libpng 1.6.43 h2797004_0
    - libsanitizer 12.3.0 h2af2641_6
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-devel_linux-64 12.3.0 h2af2641_106
    - libstdcxx-ng 13.2.0 h95c4c6d_6
    - libuuid 2.38.1 h0b41bf4_0
    - libxcb 1.15 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - meson 1.4.0 pyhd8ed1ab_0
    - ncurses 6.4.20240210 h59595ed_0
    - ninja 1.12.0 h00ab1b0_0
    - openssl 3.2.1 hd590300_1
    - pcre2 10.43 hcad00b1_0
    - pixman 0.43.2 h59595ed_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - pthread-stubs 0.4 h36c2ea0_1001
    - python 3.12.3 hab00c5b_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - sysroot_linux-64 2.12 he073ed8_17
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libice 1.1.1 hd590300_0
    - xorg-libsm 1.2.4 h7391055_0
    - xorg-libx11 1.8.9 h8ee46fc_0
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-libxext 1.3.4 h0b41bf4_2
    - xorg-libxrender 0.9.11 hd590300_0
    - xorg-renderproto 0.11.1 h7f98852_1002
    - xorg-xextproto 7.3.0 h0b41bf4_1003
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - glib 2.80.0 hf2295e7_6
    - glib-tools 2.80.0 hde27a5a_6
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 hc881cc4_6
    - libglib 2.80.0 hf2295e7_6
    - libgomp 13.2.0 hc881cc4_6
    - libiconv 1.17 hd590300_2
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-ng 13.2.0 h95c4c6d_6
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - pcre2 10.43 hcad00b1_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - libglib >=2.80.0,<3.0a0
    - libstdcxx-ng >=12
  run_constrained:
    - atk-1.0 2.38.0
test:
  commands:
    - test -f $PREFIX/lib/libatk-1.0${SHLIB_EXT}
    - test -f `pkg-config --variable=libdir --dont-define-prefix atk`/libatk-1.0${SHLIB_EXT}
  requires:
    - pkg-config
about:
  home: http://www.gtk.org/
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Accessibility Toolkit.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240423.3.1
  recipe-maintainers:
    - isuruf
    - ocefpaf
    - pkgw
    - tschoonj
  remote_url: https://github.com/conda-forge/atk-feedstock
  sha: 30237e1f664ab426f5d8ccc259007346ddd3de94
