# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Mar 13 08:11:37 2024
# ------------------------------------------------

package:
  name: nbclient
  version: 0.10.0
source:
  sha256: 4b3f1b7dba531e498449c4db4f53da339c91d449dc11e9af3a43b4eb5c5abb09
  url: https://pypi.io/packages/source/n/nbclient/nbclient-0.10.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/nbclient_1710317608672/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatchling 1.21.1 pyhd8ed1ab_0
    - importlib-metadata 7.0.2 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.1 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.1.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.3.3 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - jupyter_client >=6.1.12
    - jupyter_core >=4.12,!=5.0.*
    - nbformat >=5.1
    - python >=3.8
    - traitlets >=5.4
test:
  imports:
    - nbclient
about:
  description: 'NBClient is a tool for parameterizing and executing Jupyter Notebooks.

    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the
    jupyter_client

    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts
    to be run.

    '
  dev_url: https://github.com/jupyter/nbclient
  doc_source_url: https://github.com/jupyter/nbclient/tree/master/docs
  doc_url: https://nbclient.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240313.1.1
  recipe-maintainers:
    - davidbrochart
  remote_url: https://github.com/conda-forge/nbclient-feedstock
  sha: c5f650e66d29d83fde675931e4d1e55c1083b9b0
