# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon May 27 06:29:14 2024
# ------------------------------------------------

package:
  name: astropy-iers-data
  version: 0.2024.5.27.0.30.8
source:
  sha256: 65cd7239571d8f73fe78fc1b21bf5b2e184ff0892abaa15364c54d016ec5e0bf
  url: https://pypi.io/packages/source/a/astropy-iers-data/astropy_iers_data-0.2024.5.27.0.30.8.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/astropy-iers-data_1716791438463/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_1
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.0 h4ab18f5_3
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.11.0 hd8ed1ab_0
    - typing_extensions 4.11.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
  imports:
    - astropy_iers_data
  requires:
    - pip
about:
  home: https://github.com/astropy/astropy-iers-data/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240527.2.1
  recipe-maintainers:
    - astrofrog
    - mwcraig
  remote_url: https://github.com/conda-forge/astropy-iers-data-feedstock
  sha: 0b7d920673cff0c3d8c927ca335c527e9e154fb8
