# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Feb 24 13:06:53 2024
# ------------------------------------------------

package:
  name: libpng
  version: 1.6.43
source:
  patches:
    - patches/0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    - patches/0002-Ensure-that-lm-is-not-included-in-Windows-pkg-config.patch
  sha256: e804e465d4b109b5ad285a8fb71f0dd3f74f0068f91ce3cdfde618180c174925
  url: http://download.sourceforge.net/libpng/libpng-1.6.43.tar.gz
build:
  number: '0'
  run_exports:
    - libpng >=1.6.43,<1.7.0a0
  string: h2797004_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsanitizer 12.3.0 h0f45ef3_5
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libtool 2.4.7 h27087fc_0
    - libxcrypt 4.4.36 hd590300_1
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libzlib 1.2.13 hd590300_5
    - zlib 1.2.13 hd590300_5
  run:
    - libgcc-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libpng.a
    - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}
    - libpng-config --version
about:
  description: 'libpng is the official PNG reference library. It supports almost all
    PNG

    features, is extensible, and has been extensively tested for over 20 years.

    '
  dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
  doc_url: http://www.libpng.org/pub/png/libpng.html
  home: http://www.libpng.org/pub/png/libpng.html
  license: zlib-acknowledgement
  license_file: LICENSE
  license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
  summary: PNG reference library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240224.1.1
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pkgw
  remote_url: https://github.com/conda-forge/libpng-feedstock
  sha: 41a98d47b5f6e04fafd4cd97a32a9c672785d53f
