# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: jsonschema
  version: 4.22.0
source:
  sha256: 5b22d434a45935119af990552c862e5d6d564e8f6601206b305a61fdf661a2b7
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-4.22.0.tar.gz
build:
  entry_points:
    - jsonschema = jsonschema.cli:main
  noarch: python
  number: 0
  script: /home/conda/feedstock_root/build_artifacts/jsonschema-meta_1714573116818/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-fancy-pypi-readme 24.1.0 pyhd8ed1ab_0
    - hatch-vcs 0.4.0 pyhd8ed1ab_0
    - hatchling 1.24.2 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 hc881cc4_6
    - libgomp 13.2.0 hc881cc4_6
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.3.0 hd590300_0
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.4.10 pyhd8ed1ab_0
    - typing-extensions 4.11.0 hd8ed1ab_0
    - typing_extensions 4.11.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - attrs >=22.2.0
    - importlib_resources >=1.4.0
    - jsonschema-specifications >=2023.03.6
    - pkgutil-resolve-name >=1.3.10
    - python >=3.8
    - referencing >=0.28.4
    - rpds-py >=0.7.1
test:
  commands:
    - pip check
    - jsonschema --version
    - jsonschema --help
    - jsonschema --version | grep 4\.22\.0
  imports:
    - jsonschema
  requires:
    - pip
about:
  dev_url: https://github.com/python-jsonschema/jsonschema
  doc_source_url: https://github.com/python-jsonschema/jsonschema/blob/v4.22.0/docs/index.rst
  doc_url: https://python-jsonschema.readthedocs.org
  home: https://github.com/python-jsonschema/jsonschema
  license: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
extra:
  copy_test_source_files: true
  feedstock-name: jsonschema
  final: true
  flow_run_id: azure_20240501.2.1
  recipe-maintainers:
    - bollwyvl
    - minrk
    - nehaljwani
    - ocefpaf
  remote_url: https://github.com/conda-forge/jsonschema-feedstock
  sha: 44aece9fe7898d0970837fa4c90ba0b478fdbfb9
