# This file created by conda-build 24.5.0
# ------------------------------------------------

package:
  name: libzlib
  version: 1.2.13
source:
  sha256: 1525952a0a567581792613a9723333d7f8cc20b87a81f920fb8bc7e3f2251428
  url: https://github.com/madler/zlib/archive/refs/tags/v1.2.13.tar.gz
build:
  number: 6
  run_exports:
    - libzlib >=1.2.13,<2.0a0
  string: h4ab18f5_6
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_1
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 h58ffeeb_7
    - gcc_linux-64 12.3.0 h6477408_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_1
    - libgcc-devel_linux-64 12.3.0 h0223996_107
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libsanitizer 12.3.0 hb8811af_7
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
  run:
    - libgcc-ng >=12
  run_constrained:
    - zlib 1.2.13 *_6
test:
  commands:
    - test ! -f ${PREFIX}/lib/libz.a
    - test ! -f ${PREFIX}/lib/libz${SHLIB_EXT}
    - test ! -f ${PREFIX}/include/zlib.h
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: http://zlib.net/manual.html
  home: http://zlib.net/
  license: Zlib
  license_family: Other
  license_file: license.txt
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  feedstock-name: zlib
  final: true
  flow_run_id: azure_20240528.1.1
  recipe-maintainers:
    - groutr
    - isuruf
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/zlib-feedstock
  sha: 204eac3c5491860a24ddcea39c10e6302d6eefb6
