CI: azure
c_compiler: gcc
c_compiler_version: '12'
cairo: '1'
cdt_name: cos6
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '12'
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
expat: '2'
extend_keys:
- ignore_version
- pin_run_as_build
- extend_keys
- ignore_build_only_deps
fontconfig: '2'
fortran_compiler: gfortran
freetype: '2'
gdk_pixbuf: '2'
glib: '2'
ignore_build_only_deps:
- python
- numpy
librsvg: '2'
libwebp_base: '1'
lua: '5'
numpy: '1.22'
pango: '1.50'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.10'
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
zlib: '1.2'
