# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Sep 13 12:25:44 2023
# ------------------------------------------------

package:
  name: jupyterlab_widgets
  version: 1.1.7
source:
  sha256: 318dab34267915d658e7b0dc57433ff0ce0d52b3e283986b73b66f7ab9017ae8
  url: https://pypi.io/packages/source/j/jupyterlab_widgets/jupyterlab_widgets-1.1.7.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1694608018473/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - deprecation 2.1.0 pyh9f0ad1d_0
    - jupyter-packaging 0.12.3 pyha770c72_1
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_0
    - libgomp 13.2.0 h807b86a_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.43.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - packaging 23.1 pyhd8ed1ab_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.11.5 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomlkit 0.12.1 pyha770c72_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
  run_constrained:
    - jupyterlab >=3,<5
test:
  commands:
    - pip check
  imports:
    - jupyterlab_widgets
  requires:
    - pip
about:
  home: https://github.com/jupyter-widgets/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  summary: JupyterLab extension providing HTML widgets
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
    - jasongrout
    - jtpio
    - martinRenou
