# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Apr  4 13:55:17 2024
# ------------------------------------------------

package:
  name: nbformat
  version: 5.10.4
source:
  sha256: 322168b14f937a5d11362988ecac2a4952d3d8e3a2cbeb2319584631226d5b3a
  url: https://pypi.io/packages/source/n/nbformat/nbformat-5.10.4.tar.gz
build:
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/nbformat_1712238998817/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-nodejs-version 0.3.2 pyhd8ed1ab_0
    - hatchling 1.22.4 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.3.25 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - jsonschema >=2.6
    - jupyter_core >=4.12,!=5.0.*
    - python >=3.8
    - python-fastjsonschema >=2.15
    - traitlets >=5.1
test:
  commands:
    - pip check
    - pip list | grep -iE nbformat
    - pip list | grep -iE 'nbformat\s*5\.10\.4'
    - python -c "v = __import__('nbformat').__version__; print(v); assert v == '5.10.4'"
    - jupyter trust --version
    - jupyter-trust --help
    - pytest -vv --cov=nbformat --cov-branch --cov-report=term-missing:skip-covered
      --no-cov-on-fail --cov-fail-under=76
  imports:
    - nbformat
  requires:
    - pep440
    - pip
    - pytest
    - pytest-cov
    - testpath
  source_files:
    - tests
about:
  description: 'This package contains the base implementation of the Jupyter Notebook
    format,

    and Python APIs for working with notebooks.'
  dev_url: https://github.com/jupyter/nbformat
  doc_url: https://nbformat.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The Jupyter Notebook format
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240404.2.1
  recipe-maintainers:
    - bollwyvl
    - jakirkham
    - minrk
    - mpacer
    - ocefpaf
    - pelson
    - takluyver
  remote_url: https://github.com/conda-forge/nbformat-feedstock
  sha: 6cc0359ad2cd20691d4b0a22d05ad8b363b57710
