# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug 31 06:43:45 2020
# ------------------------------------------------

package:
    name: hpack
    version: 4.0.0
source:
    fn: hpack-4.0.0.tar.gz
    sha256: fc41de0c63e687ebffde81187a948221294896f6bdc0ae2312708df339430095
    url: https://pypi.io/packages/source/h/hpack/hpack-4.0.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: pyh9f0ad1d_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 50.0.0 py36h9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python
test:
    imports:
        - hpack
about:
    dev_url: https://github.com/python-hyper/hpack
    home: http://python-hyper.org/hpack/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: HTTP/2 Header Encoding for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astaric
        - primozgodec
