# This file created by conda-build 24.5.0
# ------------------------------------------------

package:
  name: jupyterlab_server
  version: 2.27.2
source:
  sha256: 15cbb349dc45e954e09bacf81b9f9bcb10815ff660fb2034ecd7417db3a7ea27
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-2.27.2.tar.gz
build:
  noarch: python
  number: 0
  script: /home/conda/feedstock_root/build_artifacts/jupyterlab_server-split_1716433953404/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatchling 1.24.2 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.0 h4ab18f5_2
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.5.17 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - babel >=2.10
    - importlib-metadata >=4.8.3
    - jinja2 >=3.0.3
    - json5 >=0.9.0
    - jsonschema >=4.18
    - jupyter_server >=1.21,<3
    - packaging >=21.3
    - python >=3.8
    - requests >=2.31
  run_constrained:
    - openapi-core >=0.18.0,<0.19.0
test:
  commands:
    - pip check
  downstreams:
    - jupyterlab
  imports:
    - jupyterlab_server
  requires:
    - pip
about:
  doc_url: https://jupyterlab-server.readthedocs.io
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
extra:
  copy_test_source_files: true
  feedstock-name: jupyterlab_server
  final: true
  flow_run_id: azure_20240522.2.1
  recipe-maintainers:
    - SylvainCorlay
    - afshin
    - blink1073
    - bollwyvl
    - jasongrout
    - jtpio
  remote_url: https://github.com/conda-forge/jupyterlab_server-feedstock
  sha: 2f66ab405c02cff6af3678f73c3068ca66aceb2f
