# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: importlib_metadata
  version: 7.1.0
source:
  sha256: b78938b926ee8d5f020fc4772d487045805a55ddbad2ecf21c6d60938dc7fcd2
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-7.1.0.tar.gz
build:
  noarch: generic
  number: 0
  string: hd8ed1ab_0
requirements:
  build: []
  run:
    - importlib-metadata >=7.1.0,<7.1.1.0a0
test:
  imports:
    - importlib_metadata
about:
  home: https://github.com/python/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240320.2.1
  recipe-maintainers:
    - marcelotrevisani
    - nehaljwani
    - nicoddemus
  remote_url: https://github.com/conda-forge/importlib_metadata-feedstock
  sha: 6f3fd62e5edb4bac40fea63ae475a5999290f1ee
