# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jan 27 14:09:47 2023
# ------------------------------------------------

package:
  name: fontconfig
  version: 2.14.2
source:
  patches:
    - linux-custom-paths.patch
  sha256: 3ba2dd92158718acec5caaf1a716043b5aa055c27b081d914af3ccb40dce8a55
  url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.14.2.tar.gz
build:
  binary_has_prefix_files:
    - lib/libfontconfig.so.1.*
  number: '0'
  run_exports:
    - fontconfig >=2.14.2,<3.0a0
    - fonts-conda-ecosystem
  string: h14ed4e7_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_linux-64 2.39 h5fc0e48_11
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_linux-64 11.3.0 he6f903b_11
    - gperf 3.1 h9c3ff4c_0
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 11.3.0 h239ccf8_19
    - libsqlite 3.40.0 h753d276_0
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - meson 1.0.0 pyhd8ed1ab_0
    - ncurses 6.3 h27087fc_1
    - ninja 1.11.0 h924138e_0
    - openssl 3.0.7 h0b41bf4_2
    - pkg-config 0.29.2 h36c2ea0_1008
    - python 3.10.8 h4a9ceb5_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 66.1.1 pyhd8ed1ab_0
    - sysroot_linux-64 2.12 he073ed8_15
    - tk 8.6.12 h27826a3_0
    - tzdata 2022g h191b570_0
    - xz 5.2.6 h166bdaf_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - expat 2.5.0 h27087fc_0
    - freetype 2.12.1 hca18f0e_1
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libpng 1.6.39 h753d276_0
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - zlib 1.2.13 h166bdaf_4
  run:
    - expat >=2.5.0,<3.0a0
    - freetype >=2.12.1,<3.0a0
    - libgcc-ng >=12
    - libuuid >=2.32.1,<3.0a0
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - fc-cache --help
    - fc-cat --help
    - fc-list
    - fc-match --help
    - fc-pattern --help
    - fc-query --help
    - fc-scan --help
    - fc-validate --help
    - test -f $PREFIX/lib/libfontconfig.a
    - test -f $PREFIX/lib/libfontconfig${SHLIB_EXT}
about:
  description: 'Fontconfig is a library designed to provide system-wide font configuration,

    customization and application access.

    '
  dev_url: https://cgit.freedesktop.org/fontconfig/
  doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  home: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_file: COPYING
  summary: A library for configuring and customizing font access
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pkgw
