# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Feb 13 11:42:38 2024
# ------------------------------------------------

package:
  name: pytest-metadata
  version: 3.1.1
source:
  fn: pytest-metadata-3.1.1.tar.gz
  sha256: d2a29b0355fbc03f168aa96d41ff88b1a3b44a3b02acbe491801c98a048017c8
  url: https://pypi.io/packages/source/p/pytest-metadata/pytest_metadata-3.1.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pytest-metadata_1707824627456/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-vcs 0.4.0 pyhd8ed1ab_0
    - hatchling 1.21.1 pyhd8ed1ab_0
    - importlib-metadata 7.0.1 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.1 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - packaging 23.2 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - python 3.12.1 hab00c5b_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.1.31 pyhd8ed1ab_0
    - typing-extensions 4.9.0 hd8ed1ab_0
    - typing_extensions 4.9.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - pytest >=7.0.0
    - python >=3.8
test:
  imports:
    - pytest_metadata
    - pytest_metadata.ci
about:
  home: https://github.com/pytest-dev/pytest-metadata
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin for test session metadata
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240213.1.1
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
  remote_url: https://github.com/conda-forge/pytest-metadata-feedstock
  sha: 0f7a6602dc2bf71fdfa844fc35c1c32b8d2fd906
