# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jun  7 01:13:17 2024
# ------------------------------------------------

package:
  name: tornado
  version: 6.4.1
source:
  sha256: 92d3ab53183d8c50f8204a51e6f91d18a15d5ef261e84d452800d4ff6fc504e9
  url: https://pypi.io/packages/source/t/tornado/tornado-6.4.1.tar.gz
build:
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/tornado_1717722879218/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py312h9a8786e_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_2
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 h58ffeeb_7
    - gcc_linux-64 12.3.0 h6477408_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_2
    - libgcc-devel_linux-64 12.3.0 h0223996_107
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libsanitizer 12.3.0 hb8811af_7
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_2
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands:
    - pip check
  imports:
    - tornado
    - tornado.gen
    - tornado.netutil
    - tornado.platform
    - tornado.test
  requires:
    - pip
about:
  description: 'Tornado is a Python web framework and asynchronous networking library.

    By using non-blocking network I/O, Tornado can scale to tens of thousands

    of open connections, making it ideal for long polling, WebSockets, and

    other applications that require a long-lived connection to each user.

    '
  dev_url: https://github.com/tornadoweb/tornado
  doc_source_url: https://github.com/tornadoweb/tornado/blob/stable/docs/index.rst
  doc_url: https://www.tornadoweb.org/en/stable/
  home: https://www.tornadoweb.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  license_url: https://www.apache.org/licenses/LICENSE-2.0
  summary: A Python web framework and asynchronous networking library, originally
    developed at FriendFeed.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240606.3.1
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/tornado-feedstock
  sha: 7b2adc01a07536b8626bfc62d3818a239f8ceaee
