# This file created by conda-build 3.28.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Dec 28 15:44:06 2023
# ------------------------------------------------

package:
  name: jsonschema-specifications
  version: 2023.12.1
source:
  folder: src
  sha256: 48a76787b3e70f5ed53f1160d2b81f586e4ca6d1548c5de7085d1682674764cc
  url: https://pypi.io/packages/source/j/jsonschema-specifications/jsonschema_specifications-2023.12.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/jsonschema-specifications_1703778328642/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    /home/conda/recipe_root/builder.py
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - editables 0.3 pyhd8ed1ab_0
    - hatch-vcs 0.4.0 pyhd8ed1ab_0
    - hatchling 1.21.0 pyhd8ed1ab_0
    - importlib-metadata 7.0.1 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - packaging 23.2 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 23.3.2 pyhd8ed1ab_0
    - pluggy 1.3.0 pyhd8ed1ab_0
    - pyproject_hooks 1.0.0 pyhd8ed1ab_0
    - python 3.12.1 hab00c5b_1_cpython
    - python-build 1.0.3 pyhd8ed1ab_0
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2023.11.29 pyhd8ed1ab_0
    - typing-extensions 4.9.0 hd8ed1ab_0
    - typing_extensions 4.9.0 pyha770c72_0
    - tzdata 2023d h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - importlib_resources >=1.4.0
    - python >=3.8
    - referencing >=0.31.0
test:
  commands:
    - pip check
    - coverage run --source jsonschema_specifications --branch -m pytest -vv --color=yes
      --tb=long --pyargs jsonschema_specifications
    - coverage report --show-missing --skip-covered --fail-under=96
  imports:
    - jsonschema_specifications
  requires:
    - coverage
    - pip
    - pytest
about:
  doc_url: https://jsonschema-specifications.readthedocs.io
  home: https://github.com/python-jsonschema/jsonschema-specifications
  license: MIT
  license_file: src/COPYING
  summary: The JSON Schema meta-schemas and vocabularies, exposed as a Registry
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231228.3.1
  recipe-maintainers:
    - bollwyvl
  remote_url: https://github.com/conda-forge/jsonschema-specifications-feedstock
  sha: eed30ec01cae71544a4087c632e124141af7e6e5
