# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jun  6 16:55:43 2024
# ------------------------------------------------

package:
  name: anyio
  version: 4.4.0
source:
  sha256: 5aadc6a1bbb7cdb0bede386cac5e2940f5e2ff3aa20277e991cf028e0585ce94
  url: https://pypi.io/packages/source/a/anyio/anyio-4.4.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/anyio_1717693030552/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_2
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.12.1 hd8ed1ab_0
    - typing_extensions 4.12.1 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - exceptiongroup >=1.0.2
    - idna >=2.8
    - python >=3.8
    - sniffio >=1.1
    - typing_extensions >=4.1
  run_constrained:
    - trio >=0.23
    - uvloop >=0.17
test:
  commands:
    - pytest -vv --cov=anyio --cov-branch --cov-report=term-missing:skip-covered -k="not
      (bind_link_local or block_device or connection_refused or happy_eyeballs or
      ipv6)" --cov-fail-under=86
  imports:
    - anyio
  requires:
    - coverage >=7
    - exceptiongroup >=1.2.0
    - hypothesis >=4.0
    - mock >=4
    - pip
    - psutil >=5.9
    - pytest >=7.0
    - pytest-cov
    - pytest-mock >=3.6.1
    - tomli
    - trio
    - trustme
    - uvloop
  source_files:
    - pyproject.toml
    - tests
about:
  doc_source_url: https://github.com/agronholm/anyio/tree/4.4.0/docs
  doc_url: https://anyio.readthedocs.io
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations
    on Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240606.7.1
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
  remote_url: https://github.com/conda-forge/anyio-feedstock
  sha: 988da2c6f993bcc584321fc9b112f9ad98819b10
