# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Mar 28 03:35:23 2024
# ------------------------------------------------

package:
  name: httpcore
  version: 1.0.5
source:
  sha256: 34a38e2f9291467ee3b44e89dd52615370e152954ba21721378a87b2960f7a61
  url: https://pypi.io/packages/source/h/httpcore/httpcore-1.0.5.tar.gz
build:
  noarch: python
  number: '0'
  script: '/home/conda/feedstock_root/build_artifacts/httpcore_1711596990900/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv '
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-fancy-pypi-readme 24.1.0 pyhd8ed1ab_0
    - hatchling 1.22.4 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.3.25 pyhd8ed1ab_0
    - typing-extensions 4.10.0 hd8ed1ab_0
    - typing_extensions 4.10.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - anyio >=3.0,<5.0
    - certifi
    - h11 >=0.13,<0.15
    - h2 >=3,<5
    - python >=3.8
    - sniffio ==1.*
test:
  commands:
    - pip check
  imports:
    - httpcore
  requires:
    - pip
about:
  home: https://github.com/encode/httpcore
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The next generation HTTP client.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240327.2.1
  recipe-maintainers:
    - nicoddemus
    - synapticarbors
  remote_url: https://github.com/conda-forge/httpcore-feedstock
  sha: 3e776e7804ad512001d7ee0c532e6944b5863b67
