# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Apr 21 02:36:50 2024
# ------------------------------------------------

package:
  name: pluggy
  version: 1.5.0
source:
  sha256: 2cffa88e94fdc978c4c574f15f9e59b7f4201d439195c3715ca9e2486f1d0cf1
  url: https://pypi.io/packages/source/p/pluggy/pluggy-1.5.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pluggy_1713667077545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.11.0 hd8ed1ab_0
    - typing_extensions 4.11.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
  imports:
    - pluggy
  requires:
    - pip
about:
  dev_url: https://github.com/pytest-dev/pluggy/
  doc_url: https://pluggy.readthedocs.io/en/latest/
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240420.2.1
  recipe-maintainers:
    - adriendelsalle
    - johnnygenomics
    - nicoddemus
  remote_url: https://github.com/conda-forge/pluggy-feedstock
  sha: f3e811b379ef3fada4440b01ccf33f5bd850f417
