# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Feb 21 15:53:44 2024
# ------------------------------------------------

package:
  name: httpx
  version: 0.27.0
source:
  sha256: a0cb88a46f32dc874e04ee956e4c2764aba2aa228f650b06788ba6bda2962ab5
  url: https://pypi.io/packages/source/h/httpx/httpx-0.27.0.tar.gz
build:
  entry_points:
    - httpx=httpx:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/httpx_1708530890843/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-fancy-pypi-readme 24.1.0 pyhd8ed1ab_0
    - hatchling 1.21.1 pyhd8ed1ab_0
    - importlib-metadata 7.0.1 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.1 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - packaging 23.2 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.1.0 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.1.31 pyhd8ed1ab_0
    - typing-extensions 4.9.0 hd8ed1ab_0
    - typing_extensions 4.9.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - anyio
    - certifi
    - httpcore =1.*
    - idna
    - python >=3.8
    - sniffio
test:
  commands:
    - pip check
    - httpx --help
  imports:
    - httpx
  requires:
    - click ==8.*
    - pip
    - pygments ==2.*
    - rich >=10,<13
about:
  dev_url: https://github.com/encode/httpx
  doc_url: https://www.encode.io/httpx/
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240221.2.1
  recipe-maintainers:
    - florimondmanca
    - primozgodec
    - thewchan
  remote_url: https://github.com/conda-forge/httpx-feedstock
  sha: 43f7d30f17309db5908c44104002f0e4522d3fa9
