# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: nbconvert-core
  version: 7.16.4
source:
  sha256: 86ca91ba266b0a448dc96fa6c5b9d98affabde2867b363258703536807f9f7f4
  url: https://pypi.io/packages/source/n/nbconvert/nbconvert-7.16.4.tar.gz
build:
  entry_points:
    - jupyter-dejavu = nbconvert.nbconvertapp:dejavu_main
    - jupyter-nbconvert = nbconvert.nbconvertapp:main
  noarch: python
  number: 1
  script: /home/conda/feedstock_root/build_artifacts/nbconvert-meta_1718135430380/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatchling 1.24.2 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 hf3520f5_3
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.5.22 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.19.2 pyhd8ed1ab_0
  run:
    - beautifulsoup4
    - bleach
    - defusedxml
    - entrypoints >=0.2.2
    - jinja2 >=3.0
    - jupyter_core >=4.7
    - jupyterlab_pygments
    - markupsafe >=2.0
    - mistune >=2.0.3,<4
    - nbclient >=0.5.0
    - nbformat >=5.1
    - packaging
    - pandocfilters >=1.4.1
    - pygments >=2.4.1
    - python >=3.8
    - tinycss2
    - traitlets >=5.0
  run_constrained:
    - nbconvert =7.16.4=*_1
    - pandoc >=2.9.2,<4.0.0
test:
  commands:
    - jupyter nbconvert --version
    - jupyter dejavu --version
    - jupyter nbconvert --help
    - jupyter dejavu --help
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.utils
    - nbconvert.writers
about:
  description: 'The nbconvert tool, jupyter nbconvert, converts notebooks to various
    other

    formats via Jinja templates. The nbconvert tool allows you to convert an

    .ipynb notebook file into various static formats.

    '
  dev_url: https://github.com/jupyter/nbconvert
  doc_url: https://nbconvert.readthedocs.org/
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Converting Jupyter Notebooks
extra:
  copy_test_source_files: true
  feedstock-name: nbconvert
  final: true
  flow_run_id: azure_20240611.2.1
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - jakirkham
    - jasongrout
    - martinRenou
    - minrk
    - mpacer
    - mseal
    - ocefpaf
    - pelson
    - takluyver
  remote_url: https://github.com/conda-forge/nbconvert-feedstock
  sha: 1b0de7818dc79763994b2d7072223262781ba9ca
