# This file created by conda-build 3.28.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jan 10 21:10:01 2024
# ------------------------------------------------

package:
  name: exceptiongroup
  version: 1.2.0
source:
  sha256: 91f5c769735f051a4290d52edd0858999b57e5876e9f85937691bd4c9fa3ed68
  url: https://pypi.io/packages/source/e/exceptiongroup/exceptiongroup-1.2.0.tar.gz
build:
  noarch: python
  number: '2'
  script: /home/conda/feedstock_root/build_artifacts/exceptiongroup_1704921103267/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_2
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - flit-scm 1.7.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - packaging 23.2 pyhd8ed1ab_0
    - pip 23.3.2 pyhd8ed1ab_0
    - python 3.12.1 hab00c5b_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - setuptools_scm 8.0.4 hd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.9.0 hd8ed1ab_0
    - typing_extensions 4.9.0 pyha770c72_0
    - tzdata 2023d h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
  imports:
    - exceptiongroup
  requires:
    - pip
about:
  dev_url: https://github.com/agronholm/exceptiongroup
  doc_url: https://docs.python.org/3/library/exceptions.html
  home: https://pypi.org/project/exceptiongroup/
  license: MIT and PSF-2.0
  license_file: LICENSE
  summary: Backport of PEP 654 (exception groups)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240110.6.1
  recipe-maintainers:
    - xylar
  remote_url: https://github.com/conda-forge/exceptiongroup-feedstock
  sha: 1a5ebacda04587da74ce070e2eb25e026e1bb338
