# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Nov  2 09:15:14 2020
# ------------------------------------------------

package:
    name: toml
    version: 0.10.2
source:
    fn: toml-0.10.2.tar.gz
    sha256: b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f
    url: https://pypi.io/packages/source/t/toml/toml-0.10.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/toml_1604308577558/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps -vv
    string: pyhd8ed1ab_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py39h079e4ff_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.4 py_0
        - python 3.9.0 h2a148a8_4_cpython
        - python_abi 3.9 1_cp39
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py39h079e4ff_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - tzdata 2020d h516909a_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - python >=2.7
test:
    commands:
        - conda inspect linkages -p $PREFIX toml
    imports:
        - toml
about:
    home: https://github.com/uiri/toml
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python lib for TOML.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - holgern
        - rlaverde
