# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Dec 17 21:31:33 2020
# ------------------------------------------------

package:
    name: recommonmark
    version: 0.7.1
source:
    sha256: bdb4db649f2222dcd8d2d844f0006b958d627f732415d399791ee436a3686d67
    url: https://pypi.io/packages/source/r/recommonmark/recommonmark-0.7.1.tar.gz
build:
    entry_points:
        - cm2html = recommonmark.scripts:cm2html
        - cm2latex = recommonmark.scripts:cm2latex
        - cm2man = recommonmark.scripts:cm2man
        - cm2pseudoxml = recommonmark.scripts:cm2pseudoxml
        - cm2xetex = recommonmark.scripts:cm2xetex
        - cm2xml = recommonmark.scripts:cm2xml
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/recommonmark_1608240755822/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . -vv
    string: pyhd8ed1ab_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.12.5 ha878542_0
        - certifi 2020.12.5 py39hf3d152e_0
        - ld_impl_linux-64 2.35.1 hea4e1c9_1
        - libffi 3.3 h58526e2_2
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 h58526e2_4
        - openssl 1.1.1i h7f98852_0
        - pip 20.3.3 pyhd8ed1ab_0
        - python 3.9.1 hffdb5ce_1_cpython
        - python_abi 3.9 1_cp39
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py39h079e4ff_2
        - sqlite 3.34.0 h74cdb3f_0
        - tk 8.6.10 h21135ba_1
        - tzdata 2020d h516909a_0
        - wheel 0.36.2 pyhd3deb0d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - commonmark >=0.8.1
        - docutils >=0.11
        - python >=3
        - sphinx >=1.3.1
test:
    commands:
        - pip check
        - cm2html --help
        - cm2latex --help
        - cm2man --help
        - cm2pseudoxml --help
        - cm2xetex --help
        - cm2xml --help
    imports:
        - recommonmark
    requires:
        - pip
about:
    description: 'A docutils-compatibility bridge to CommonMark.

        This allows you to write CommonMark inside of Docutils & Sphinx projects.

        '
    dev_url: https://github.com/rtfd/recommonmark
    doc_url: http://recommonmark.readthedocs.org
    home: https://github.com/rtfd/recommonmark
    license: MIT
    license_family: MIT
    license_file: license.md
    summary: A docutils-compatibility bridge to CommonMark
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CJ-Wright
        - ocefpaf
