CI: azure
bzip2: '1'
c_compiler: gcc
c_compiler_version: '12'
c_stdlib: sysroot
c_stdlib_version: '2.12'
cdt_name: cos6
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '12'
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fortran_compiler: gfortran
hdf5: 1.14.3
ignore_build_only_deps:
- python
- numpy
lua: '5'
lzo: '2'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: 3.12.* *_cpython
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - python
  - numpy
- - c_compiler_version
  - cxx_compiler_version
- - c_stdlib_version
  - cdt_name
zlib: '1.2'
