# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct  1 02:54:33 2023
# ------------------------------------------------

package:
  name: arrow
  version: 1.3.0
source:
  sha256: d4540617648cb5f895730f1ad8c82a65f2dad0166f57b75f3ca54759c4d67a85
  url: https://pypi.io/packages/source/a/arrow/arrow-1.3.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/arrow_1696128962909/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libnsl 2.0.0 hd590300_1
    - libsqlite 3.43.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.3 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.11.5 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 h2797004_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
    - python-dateutil >=2.7.0
    - types-python-dateutil >=2.8.10
test:
  commands:
    - pip check
    - pytest --cov=arrow --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail
      --cov-fail-under=99 -k "not parse_tz_name_zzz"
  requires:
    - dateparser >=1,<2
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - pytz
    - simplejson >=3,<4
  source_files:
    - tests
about:
  description: 'Arrow is a Python library that offers a sensible, human-friendly approach
    to

    creating, manipulating, formatting and converting dates, times, and timestamps.

    It implements and updates the datetime type, plugging gaps in functionality,

    and provides an intelligent module API that supports many common creation

    scenarios. Simply put, it helps you work with dates and times with fewer

    imports and a lot less code.

    '
  doc_source_url: https://github.com/arrow-py/arrow/tree/1.3.0/docs
  doc_url: https://arrow.readthedocs.io
  home: https://github.com/arrow-py/arrow
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Better dates & times for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
