# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon May 27 19:38:03 2024
# ------------------------------------------------

package:
  name: nbclassic
  version: 1.1.0
source:
  sha256: 77b77ba85f9e988f9bad85df345b514e9e64c7f0e822992ab1df4a78ac64fc1e
  url: https://pypi.io/packages/source/n/nbclassic/nbclassic-1.1.0.tar.gz
build:
  entry_points:
    - jupyter-nbclassic = nbclassic.notebookapp:main
    - jupyter-nbclassic-bundlerextension = nbclassic.bundler.bundlerextensions:main
    - jupyter-nbclassic-extension = nbclassic.nbextensions:main
    - jupyter-nbclassic-serverextension = nbclassic.serverextensions:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/nbclassic_1716838762700/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vvv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - anyio 4.3.0 pyhd8ed1ab_0
    - argon2-cffi 23.1.0 pyhd8ed1ab_0
    - argon2-cffi-bindings 21.2.0 py312h98912ed_4
    - arrow 1.3.0 pyhd8ed1ab_0
    - attrs 23.2.0 pyh71513ae_0
    - babel 2.14.0 pyhd8ed1ab_0
    - beautifulsoup4 4.12.3 pyha770c72_0
    - bleach 6.1.0 pyhd8ed1ab_0
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - cached-property 1.5.2 hd8ed1ab_1
    - cached_property 1.5.2 pyha770c72_1
    - cffi 1.16.0 py312hf06ca03_0
    - defusedxml 0.7.1 pyhd8ed1ab_0
    - deprecation 2.1.0 pyh9f0ad1d_0
    - entrypoints 0.4 pyhd8ed1ab_0
    - exceptiongroup 1.2.0 pyhd8ed1ab_2
    - fqdn 1.5.1 pyhd8ed1ab_0
    - idna 3.7 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - importlib_metadata 7.1.0 hd8ed1ab_0
    - importlib_resources 6.4.0 pyhd8ed1ab_0
    - isoduration 20.11.0 pyhd8ed1ab_0
    - jinja2 3.1.4 pyhd8ed1ab_0
    - jsonpointer 2.4 py312h7900ff3_3
    - jsonschema 4.22.0 pyhd8ed1ab_0
    - jsonschema-specifications 2023.12.1 pyhd8ed1ab_0
    - jsonschema-with-format-nongpl 4.22.0 pyhd8ed1ab_0
    - jupyter-packaging 0.12.3 pyha770c72_1
    - jupyter_client 8.6.2 pyhd8ed1ab_0
    - jupyter_core 5.7.2 py312h7900ff3_0
    - jupyter_events 0.10.0 pyhd8ed1ab_0
    - jupyter_server 2.14.0 pyhd8ed1ab_0
    - jupyter_server_terminals 0.5.3 pyhd8ed1ab_0
    - jupyterlab_pygments 0.3.0 pyhd8ed1ab_1
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 hf3520f5_1
    - libedit 3.1.20191231 he28a2e2_2
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsodium 1.0.18 h36c2ea0_1
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - markupsafe 2.1.5 py312h98912ed_0
    - mistune 3.0.2 pyhd8ed1ab_0
    - nbclient 0.10.0 pyhd8ed1ab_0
    - nbconvert-core 7.16.4 pyhd8ed1ab_0
    - nbformat 5.10.4 pyhd8ed1ab_0
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.0 h4ab18f5_3
    - overrides 7.7.0 pyhd8ed1ab_0
    - packaging 24.0 pyhd8ed1ab_0
    - pandocfilters 1.5.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pkgutil-resolve-name 1.3.10 pyhd8ed1ab_1
    - platformdirs 4.2.2 pyhd8ed1ab_0
    - prometheus_client 0.20.0 pyhd8ed1ab_0
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pycparser 2.22 pyhd8ed1ab_0
    - pygments 2.18.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - python-dateutil 2.9.0 pyhd8ed1ab_0
    - python-fastjsonschema 2.19.1 pyhd8ed1ab_0
    - python-json-logger 2.0.7 pyhd8ed1ab_0
    - python_abi 3.12 4_cp312
    - pytz 2024.1 pyhd8ed1ab_0
    - pyyaml 6.0.1 py312h98912ed_1
    - pyzmq 26.0.3 py312h8fd38d8_0
    - readline 8.2 h8228510_1
    - referencing 0.35.1 pyhd8ed1ab_0
    - rfc3339-validator 0.1.4 pyhd8ed1ab_0
    - rfc3986-validator 0.1.1 pyh9f0ad1d_0
    - rpds-py 0.18.1 py312h4413252_0
    - send2trash 1.8.3 pyh0d859eb_0
    - setuptools 70.0.0 pyhd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - sniffio 1.3.1 pyhd8ed1ab_0
    - soupsieve 2.5 pyhd8ed1ab_1
    - terminado 0.18.1 pyh0d859eb_0
    - tinycss2 1.3.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomlkit 0.12.5 pyha770c72_0
    - tornado 6.4 py312h98912ed_0
    - traitlets 5.14.3 pyhd8ed1ab_0
    - types-python-dateutil 2.9.0.20240316 pyhd8ed1ab_0
    - typing-extensions 4.11.0 hd8ed1ab_0
    - typing_extensions 4.11.0 pyha770c72_0
    - typing_utils 0.1.0 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - uri-template 1.3.0 pyhd8ed1ab_0
    - webcolors 1.13 pyhd8ed1ab_0
    - webencodings 0.5.1 pyhd8ed1ab_2
    - websocket-client 1.8.0 pyhd8ed1ab_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - yaml 0.2.5 h7f98852_2
    - zeromq 4.3.5 h75354e8_4
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - ipykernel
    - ipython_genutils
    - nest-asyncio >=1.5
    - notebook-shim >=0.2.3
    - python >=3.7
test:
  commands:
    - pip check
    - jupyter nbclassic --help
    - jupyter nbclassic-extension --help
    - jupyter nbclassic-serverextension --help
    - jupyter nbclassic-bundlerextension --help
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep -iE "nbclassic.*enabled"
    - cat server_extensions | grep -iE "nbclassic.*OK"
  downstreams:
    - jupyterlab
    - jupyterlab_server
  imports:
    - nbclassic
  requires:
    - pip
about:
  description: 'The Jupyter NbClassic is a web application that allows you to create
    and

    share documents that contain live code, equations, visualizations, and

    explanatory text. The NbClassic has support for multiple programming

    languages, sharing, and interactive widgets.

    '
  doc_url: https://jupyter-notebook.readthedocs.io
  home: http://github.com/jupyterlab/nbclassic
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A web-based notebook environment for interactive computing
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240527.5.1
  recipe-maintainers:
    - afshin
    - bollwyvl
    - jasongrout
    - jtpio
  remote_url: https://github.com/conda-forge/nbclassic-feedstock
  sha: 0fa6ea13a57d7fcc64e9ae32c952d96046ef2b5a
