# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jan 29 17:26:10 2024
# ------------------------------------------------

package:
  name: pixman
  version: 0.43.2
source:
  patches:
    - meson-darwin-versions.patch
  sha256: ea79297e5418fb528d0466e8b5b91d1be88857fa3706f49777b2925a72ae9924
  url: http://cairographics.org/releases/pixman-0.43.2.tar.gz
build:
  number: '0'
  run_exports:
    - pixman >=0.43.2,<1.0a0
  string: h59595ed_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_4
    - gcc_linux-64 12.3.0 h76fc315_2
    - gxx_impl_linux-64 12.3.0 he2b93b0_4
    - gxx_linux-64 12.3.0 h8a814eb_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_104
    - libgcc-ng 13.2.0 h807b86a_4
    - libgomp 13.2.0 h807b86a_4
    - libnsl 2.0.1 hd590300_0
    - libsanitizer 12.3.0 h0f45ef3_4
    - libsqlite 3.44.2 h2797004_0
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_104
    - libstdcxx-ng 13.2.0 h7e041cc_4
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - meson 1.3.1 pyhd8ed1ab_0
    - ncurses 6.4 h59595ed_2
    - ninja 1.11.1 h924138e_0
    - openssl 3.2.0 hd590300_1
    - pkg-config 0.29.2 h36c2ea0_1008
    - python 3.12.1 hab00c5b_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - sysroot_linux-64 2.12 he073ed8_16
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023d h0c530f3_0
    - xz 5.2.6 h166bdaf_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_4
    - libgomp 13.2.0 h807b86a_4
    - libstdcxx-ng 13.2.0 h7e041cc_4
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
test:
  commands:
    - test -f ${PREFIX}/lib/libpixman-1.a
about:
  description: 'Pixman is a low-level software library for pixel manipulation, providing

    features such as image compositing and trapezoid rasterization.

    '
  dev_url: https://cgit.freedesktop.org/pixman/
  home: http://www.pixman.org/
  license: MIT
  license_file: COPYING
  summary: A low-level software library for pixel manipulation.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240129.1.1
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
    - sdvillal
  remote_url: https://github.com/conda-forge/pixman-feedstock
  sha: d7eace89e954e22af2bba9af2f347419d2ce7174
