# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Apr 19 19:27:03 2024
# ------------------------------------------------

package:
  name: sphinx
  version: 7.3.7
source:
  sha256: a4a7db75ed37531c05002d56ed6948d4c42f473a36f46e1382b0bd76ca9627bc
  url: https://pypi.io/packages/source/s/sphinx/sphinx-7.3.7.tar.gz
build:
  entry_points:
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/sphinx_1713554891974/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - babel 2.14.0 pyhd8ed1ab_0
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_1
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - pytz 2024.1 pyhd8ed1ab_0
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - alabaster >=0.7.14,<0.8.dev0
    - babel >=2.9
    - colorama >=0.4.5
    - docutils >=0.18.1,<0.22
    - imagesize >=1.3
    - importlib-metadata >=4.8
    - jinja2 >=3.0
    - packaging >=21.0
    - pygments >=2.14
    - python >=3.9
    - requests >=2.25.0
    - snowballstemmer >=2.0
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp >=2.0.0
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml >=1.1.9
    - tomli >=2.0
test:
  commands:
    - pip check
    - sphinx-quickstart --version
  imports:
    - sphinx
    - sphinx.builders
  requires:
    - pip
about:
  description: 'Sphinx makes it easy to create intelligent and beautiful documentation.


    Sphinx uses reStructuredText as its markup language, and many of its strengths

    come from the power and straightforwardness of reStructuredText and its parsing

    and translating suite, the Docutils.

    '
  dev_url: https://github.com/sphinx-doc/sphinx
  doc_url: https://www.sphinx-doc.org/en/master/
  home: https://www.sphinx-doc.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: Sphinx makes it easy to create intelligent and beautiful documentation.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240419.2.1
  recipe-maintainers:
    - AA-Turner
    - blink1073
    - ccordoba12
    - jakirkham
    - matthiasdiener
    - ocefpaf
  remote_url: https://github.com/conda-forge/sphinx-feedstock
  sha: 524153c59452f0cfae8abb6d2bba50935c0b32a2
