# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Apr  6 18:57:02 2024
# ------------------------------------------------

package:
  name: contourpy
  version: 1.2.1
source:
  sha256: 4d8908b3bee1c889e547867ca4cdc54e5ab6be6d3e078556814a22457f49423c
  url: https://pypi.io/packages/source/c/contourpy/contourpy-1.2.1.tar.gz
build:
  number: '0'
  string: py310hd41b1e2_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 he2b93b0_5
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsanitizer 12.3.0 h0f45ef3_5
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_105
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - meson 1.4.0 pyhd8ed1ab_0
    - meson-python 0.15.0 pyh0c530f3_0
    - ncurses 6.4.20240210 h59595ed_0
    - ninja 1.11.1 h924138e_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - pybind11 2.12.0 py310hd41b1e2_0
    - pybind11-global 2.12.0 py310hd41b1e2_0
    - pyproject-metadata 0.7.1 pyhd8ed1ab_0
    - python 3.10.14 hd12c33a_0_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - numpy >=1.20
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pip check
    - python -c "import contourpy as c; print(c.contour_generator(z=[[0, 1], [2, 3]]).lines(0.9))"
    - python -c "from contourpy.util import build_config; from pprint import pprint;
      pprint(build_config())"
    - python -c "import platform, sys; print(sys.version, platform.uname())"
  imports:
    - contourpy
    - contourpy.util
  requires:
    - pip
about:
  description: 'ContourPy is a Python library for calculating contours of 2D quadrilateral

    grids.  It is written in C++11 and wrapped using pybind11.

    '
  doc_url: https://contourpy.readthedocs.io
  home: https://github.com/contourpy/contourpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python library for calculating contours of 2D quadrilateral grids.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240406.11.1
  recipe-maintainers:
    - ianthomas23
  remote_url: https://github.com/conda-forge/contourpy-feedstock
  sha: 13acab3f41e47b207abd9a06db2ae665afb7d2e2
