# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Apr  6 17:52:13 2024
# ------------------------------------------------

package:
  name: sphinx-automodapi
  version: 0.17.0
source:
  sha256: 7ccdadad57add4aa9149d9f2bb5cf28c8f8b590280b4735b1156ea8355c423a1
  url: https://pypi.io/packages/source/s/sphinx-automodapi/sphinx-automodapi-0.17.0.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/sphinx-automodapi_1712426001947/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyh717bed2_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.11.0 hd8ed1ab_0
    - typing_extensions 4.11.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
    - sphinx >=4
test:
  commands:
    - python -m pip check sphinx-automodapi
    - python -m pip show sphinx-automodapi
    - python -m pytest -ra --pyargs sphinx_automodapi -k 'not cython'
  imports:
    - sphinx_automodapi
  requires:
    - graphviz
    - pip
    - pytest >=4.6
about:
  description: 'This is a Sphinx extension to automatically generate API pages for
    whole

    modules.

    '
  dev_url: https://github.com/astropy/sphinx-automodapi
  doc_url: https://github.com/astropy/sphinx-automodapi
  home: https://github.com/astropy/sphinx-automodapi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Sphinx extension for auto-generating API documentation for entire modules
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240406.3.1
  recipe-maintainers:
    - astrofrog
    - bsipocz
    - drdavella
    - mwcraig
  remote_url: https://github.com/conda-forge/sphinx-automodapi-feedstock
  sha: 633f199a791248eda66da9d2d52254878f375cff
