# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue May 21 07:58:35 2024
# ------------------------------------------------

package:
  name: ipython_genutils
  version: 0.2.0
source:
  fn: ipython_genutils-0.2.0.tar.gz
  sha256: eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8
  url: https://pypi.io/packages/source/i/ipython_genutils/ipython_genutils-0.2.0.tar.gz
build:
  noarch: python
  number: '1'
  script: python -m pip install --no-deps --ignore-installed .
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.0 h4ab18f5_1
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=2.7
test:
  imports:
    - ipython_genutils
    - ipython_genutils.testing
    - ipython_genutils.tests
about:
  home: http://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Vestigial utilities from IPython
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240521.2.1
  recipe-maintainers:
    - Carreau
    - minrk
    - msarahan
    - pelson
    - scopatz
    - takluyver
  remote_url: https://github.com/conda-forge/ipython_genutils-feedstock
  sha: 082f8e636e8efac16433f663bbc48159631af060
