# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Apr 20 15:19:17 2024
# ------------------------------------------------

package:
  name: radioactivedecay
  version: 0.5.0
source:
  sha256: 0ba2e6eae4f69ecbff77cfac08e6f569006f012686808d430fa7add123c55983
  url: https://pypi.io/packages/source/r/radioactivedecay/radioactivedecay-0.5.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/radioactivedecay_1713626431589/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - importlib_resources
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - python >=3.8
    - scipy
    - setuptools
    - sympy
test:
  commands:
    - pip check
    - python -m unittest discover
  imports:
    - radioactivedecay
  requires:
    - pip
  source_files:
    - tests/
about:
  description: 'A Python package for radioactive decay modelling that supports 1252

    radionuclides, decay chains, branching, and metastable states.

    '
  dev_url: https://github.com/radioactivedecay/radioactivedecay
  doc_url: https://radioactivedecay.github.io
  home: https://github.com/radioactivedecay/radioactivedecay
  license: MIT AND LicenseRef-AMDC AND LicenseRef-ICRP-07
  license_file:
    - LICENSE
    - LICENSE.AMDC
    - LICENSE.ICRP-07
  summary: Radioactive decay calculations in Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240420.3.1
  recipe-maintainers:
    - alexmalins
  remote_url: https://github.com/conda-forge/radioactivedecay-feedstock
  sha: cda145ed894dd4a2c38cd6285550bb0170774a9e
