# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed May  8 00:10:53 2024
# ------------------------------------------------

package:
  name: jinja2
  version: 3.1.4
source:
  sha256: 4a3aee7acbbe7303aede8e9648d13b8bf88a429282aa6122a993f0ac800cb369
  url: https://pypi.io/packages/source/j/jinja2/jinja2-3.1.4.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/jinja2_1715127149914/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps -vv --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_1
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.3.0 hd590300_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - markupsafe >=2.0
    - python >=3.7
test:
  commands:
    - pip check
  imports:
    - jinja2
  requires:
    - pip
about:
  description: "Jinja is a fast, expressive, extensible templating engine. Special\n\
    placeholders in the template allow writing code similar to Python\nsyntax. Then\
    \ the template is passed data to render the final document.\n\nIt includes:\n\n\
    -   Template inheritance and inclusion.\n-   Define and import macros within templates.\n\
    -   HTML templates can use autoescaping to prevent XSS from untrusted\n    user\
    \ input.\n-   A sandboxed environment can safely render untrusted templates.\n\
    -   AsyncIO support for generating templates and calling async\n    functions.\n\
    -   I18N support with Babel.\n-   Templates are compiled to optimized Python code\
    \ just-in-time and\n    cached, or can be compiled ahead-of-time.\n-   Exceptions\
    \ point to the correct line in templates to make debugging\n    easier.\n-   Extensible\
    \ filters, tests, functions, and even syntax.\n\nJinja's philosophy is that while\
    \ application logic belongs in Python if\npossible, it shouldn't make the template\
    \ designer's job difficult by\nrestricting functionality too much.\n"
  dev_url: https://github.com/pallets/jinja/
  doc_url: https://jinja.palletsprojects.com/
  home: https://palletsprojects.com/p/jinja/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A very fast and expressive template engine.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240507.2.1
  recipe-maintainers:
    - bollwyvl
    - jakirkham
    - msarahan
    - nehaljwani
    - scopatz
    - xylar
  remote_url: https://github.com/conda-forge/jinja2-feedstock
  sha: 1e8bac11ccb173e5ce6a2aa2ba6750f984ee507a
