# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Sep 22 19:10:05 2023
# ------------------------------------------------

package:
  name: typed-ast
  version: 1.5.5
source:
  sha256: 94282f7a354f36ef5dbce0ef3467ebf6a258e370ab33d5b40c249fa996e590dd
  url: https://pypi.io/packages/source/t/typed_ast/typed_ast-1.5.5.tar.gz
build:
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/typed-ast_1695409889284/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: py312h98912ed_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_2
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_2
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libsanitizer 12.3.0 h0f45ef3_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.43.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.3 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.12.0rc3 rc3_h124a313_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - python >=3.12.0rc3,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands:
    - pip check
  imports:
    - typed_ast
  requires:
    - pip
about:
  description: 'typed_ast is a Python 3 package that provides a Python 2.7 and Python
    3

    parser similar to the standard ast library. Unlike ast, the parsers in

    typed_ast include PEP 484 type comments and are independent of the version

    of Python under which they are run. The typed_ast parsers produce the

    standard Python AST (plus type comments), and are both fast and correct, as

    they are based on the CPython 2.7 and 3.6 parsers.

    '
  dev_url: https://github.com/python/typed_ast
  doc_url: https://github.com/python/typed_ast/blob/master/README.md
  home: https://github.com/python/typed_ast
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: a fork of Python 2 and 3 ast modules with type comment support
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
