# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jun 25 11:28:44 2024
# ------------------------------------------------

package:
  name: tenacity
  version: 8.4.2
source:
  sha256: cd80a53a79336edba8489e767f729e4f391c896956b57140b5d7511a64bbd3ef
  url: https://pypi.io/packages/source/t/tenacity/tenacity-8.4.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/tenacity_1719315008981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install -vv .
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_13
    - libgomp 13.2.0 h77fa898_13
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - packaging 24.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.4 h194c7f8_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.1.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
  imports:
    - tenacity
  requires:
    - pip
about:
  description: 'Tenacity is general-purpose retrying library, written in Python, to
    simplify the task of

    adding retry behavior to just about anything. It originates from a fork of Retrying

    '
  dev_url: http://github.com/jd/tenacity
  doc_url: http://tenacity.readthedocs.io
  home: http://github.com/jd/tenacity
  license: Apache-2.0
  license_file: LICENSE
  summary: Retry a flaky function whenever an exception occurs until it works
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240625.1.1
  recipe-maintainers:
    - sodre
    - xylar
  remote_url: https://github.com/conda-forge/tenacity-feedstock
  sha: 96843fbbad5f9c3bd91efb0bad49ff1628ef3cc1
