# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jun 20 06:51:00 2024
# ------------------------------------------------

package:
  name: zstandard
  version: 0.22.0
source:
  patches:
    - zstd_1.5.6.patch
  sha256: 8226a33c542bcb54cd6bd0a366067b610b41713b64c9abec1bc4533d69f51e70
  url: https://pypi.io/packages/source/z/zstandard/zstandard-0.22.0.tar.gz
build:
  number: '1'
  string: py312h5b18bf6_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_7
    - gcc_impl_linux-64 12.3.0 h58ffeeb_10
    - gcc_linux-64 12.3.0 h9528a6a_7
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.3.0 h6b66f73_110
    - libgcc-ng 13.2.0 h77fa898_10
    - libgomp 13.2.0 h77fa898_10
    - libsanitizer 12.3.0 hb8811af_10
    - libstdcxx-ng 13.2.0 hc0a3c3a_10
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - cffi 1.16.0 py312hf06ca03_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_10
    - libgomp 13.2.0 h77fa898_10
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_10
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pip 24.0 pyhd8ed1ab_0
    - pycparser 2.22 pyhd8ed1ab_0
    - python 3.12.4 h194c7f8_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  run:
    - cffi >=1.11
    - libgcc-ng >=12
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
    - zstd >=1.5.6,<1.5.7.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240620.1.1
  recipe-maintainers:
    - pavelzw
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstandard-feedstock
  sha: 5a4bf32afb530365fe38d9905069daeb3391634e
