# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Apr 13 05:28:38 2024
# ------------------------------------------------

package:
  name: json5
  version: 0.9.25
source:
  sha256: 548e41b9be043f9426776f05df8635a00fe06104ea51ed24b67f908856e151ae
  url: https://pypi.io/packages/source/j/json5/json5-0.9.25.tar.gz
build:
  entry_points:
    - pyjson5=json5.tool:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/json5_1712986206667/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7,<4.0
test:
  commands:
    - pip check
    - pyjson5 --help
  imports:
    - json5
  requires:
    - pip
about:
  home: https://github.com/dpranke/pyjson5
  license: Apache-2.0
  license_file: LICENSE
  summary: A Python implementation of the JSON5 data format.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240413.2.1
  recipe-maintainers:
    - ian-r-rose
    - rxm7706
  remote_url: https://github.com/conda-forge/json5-feedstock
  sha: 469e6d18618ca1de0b3a3d3c079bd87abade6638
