# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Feb 26 13:07:20 2024
# ------------------------------------------------

package:
  name: sniffio
  version: 1.3.1
source:
  sha256: f4324edc670a0f49750a81b895f35c3adb843cca46f0530f79fc1babb23789dc
  url: https://pypi.io/packages/source/s/sniffio/sniffio-1.3.1.tar.gz
build:
  noarch: python
  number: '0'
  script: '/home/conda/feedstock_root/build_artifacts/sniffio_1708952932303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.1 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.1.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  imports:
    - sniffio
about:
  doc_url: https://sniffio.readthedocs.io
  home: https://github.com/python-trio/sniffio
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.APACHE2
  summary: Sniff out which async library your code is running under
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240226.1.1
  recipe-maintainers:
    - nicoddemus
  remote_url: https://github.com/conda-forge/sniffio-feedstock
  sha: e3fc0c462ca6ff566b086489ab8801f365dc81f6
