# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun 10 09:53:00 2024
# ------------------------------------------------

package:
  name: zipp
  version: 3.19.2
source:
  sha256: bf1dcf6450f873a13e952a29504887c89e6de7506209e5b1bcc3460135d4de19
  url: https://pypi.io/packages/source/z/zipp/zipp-3.19.2.tar.gz
build:
  noarch: python
  number: '0'
  script: '/home/conda/feedstock_root/build_artifacts/zipp_1718013267051/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps --ignore-installed -vv '
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_3
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - setuptools-scm 6.4.2 pyhd8ed1ab_0
    - setuptools_scm 6.4.2 hd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - toml 0.10.2 pyhd8ed1ab_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - python -m unittest tests/test_path.py
    - pip check
  imports:
    - zipp
  requires:
    - func_timeout
    - importlib_metadata
    - jaraco.functools
    - jaraco.itertools
    - jaraco.test
    - more-itertools
    - pip
  source_files:
    - tests
about:
  dev_url: https://github.com/jaraco/zipp
  doc_url: https://zipp.readthedocs.io/en/latest
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240610.8.1
  recipe-maintainers:
    - jan-janssen
    - nehaljwani
  remote_url: https://github.com/conda-forge/zipp-feedstock
  sha: e5bd9fdcab2413fc4c7399400040634bc5421a3f
