# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Apr 30 09:02:14 2024
# ------------------------------------------------

package:
  name: sphinx-gallery
  version: 0.16.0
source:
  sha256: 3912765bc5e7b5451dc471ad50ead808a9752280b23fd2ec4277719a5ef68e42
  url: https://pypi.io/packages/source/s/sphinx-gallery/sphinx_gallery-0.16.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/sphinx-gallery_1714467801378/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 hc881cc4_6
    - libgomp 13.2.0 hc881cc4_6
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.11.0 hd8ed1ab_0
    - typing_extensions 4.11.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - pillow
    - python >=3.8
    - sphinx >=4
test:
  commands:
    - pip check
  imports:
    - sphinx_gallery
    - sphinx_gallery.gen_gallery
  requires:
    - pip
about:
  description: 'A Sphinx extension that builds an HTML gallery of examples from any
    set of

    Python scripts. It is extracted from the scikit-learn project and aims to

    be an independent general purpose extension.

    '
  dev_url: https://github.com/sphinx-gallery/sphinx-gallery
  doc_url: https://sphinx-gallery.github.io
  home: https://github.com/sphinx-gallery/sphinx-gallery
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for automatic generation of an example gallery
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240430.1.1
  recipe-maintainers:
    - dfroger
    - dopplershift
    - leouieda
    - ocefpaf
  remote_url: https://github.com/conda-forge/sphinx-gallery-feedstock
  sha: 85e647022e2695b2b0ad145bf4285e1f786a7340
