# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 16 13:13:58 2022
# ------------------------------------------------

package:
  name: lerc
  version: 4.0.0
source:
  sha256: 91431c2b16d0e3de6cbaea188603359f87caed08259a645fd5a3805784ee30a0
  url: https://github.com/Esri/lerc/archive/v4.0.0.tar.gz
build:
  number: '0'
  run_exports:
    - lerc >=4.0.0,<5.0a0
  string: h27087fc_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_10
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.18.1 h7f98852_0
    - ca-certificates 2022.6.15 ha878542_0
    - cmake 3.23.2 h5432695_0
    - expat 2.4.8 h27087fc_0
    - gcc_impl_linux-64 10.3.0 hf2f2afa_16
    - gcc_linux-64 10.3.0 hc39de41_10
    - gxx_impl_linux-64 10.3.0 hf2f2afa_16
    - gxx_linux-64 10.3.0 h2593f52_10
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.19.3 h08a2579_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libcurl 7.83.1 h2283fc2_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libgcc-devel_linux-64 10.3.0 he6cfe16_16
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libnghttp2 1.47.0 he49606f_0
    - libsanitizer 10.3.0 h26c7422_16
    - libssh2 1.10.0 ha35d2d1_2
    - libstdcxx-devel_linux-64 10.3.0 he6cfe16_16
    - libstdcxx-ng 12.1.0 ha89aaad_16
    - libuv 1.44.2 h166bdaf_0
    - libzlib 1.2.12 h166bdaf_2
    - lz4-c 1.9.3 h9c3ff4c_1
    - make 4.3 hd18ef5c_1
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.5 h166bdaf_0
    - rhash 1.4.3 h166bdaf_0
    - sysroot_linux-64 2.12 he073ed8_15
    - xz 5.2.5 h516909a_1
    - zlib 1.2.12 h166bdaf_2
    - zstd 1.5.2 h8a70e8d_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libstdcxx-ng 12.1.0 ha89aaad_16
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
test:
  commands:
    - test -f ${PREFIX}/lib/libLerc${SHLIB_EXT}
    - test -f ${PREFIX}/include/Lerc_types.h
about:
  description: 'LERC is an open-source image or raster format which

    supports rapid encoding and decoding for any pixel type

    (not just RGB or Byte). Users set the maximum compression

    error per pixel while encoding, so the precision of the

    original input image is preserved (within user defined

    error bounds).

    '
  home: https://github.com/Esri/lerc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LERC - Limited Error Raster Compression
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
