# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Mar 17 23:10:19 2023
# ------------------------------------------------

package:
  name: zlib-ng
  version: 2.0.7
source:
  fn: zstd-ng.tar.gz
  sha256: 6c0853bb27738b811f2b4d4af095323c3d5ce36ceed6b50e5f773204fb8f7200
  url: https://codeload.github.com/zlib-ng/zlib-ng/tar.gz/refs/tags/2.0.7
build:
  number: '0'
  run_exports:
    - zlib-ng >=2.0.7,<2.1.0a0
  string: h0b41bf4_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_linux-64 2.39 h5fc0e48_11
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.18.1 h7f98852_0
    - ca-certificates 2022.12.7 ha878542_0
    - cmake 3.26.0 h077f3f9_0
    - expat 2.5.0 h27087fc_0
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_linux-64 11.3.0 he6f903b_11
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.20.1 h81ceb04_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libcurl 7.88.1 hdc1c0ab_1
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnghttp2 1.52.0 h61bc06f_0
    - libsanitizer 11.3.0 h239ccf8_19
    - libssh2 1.10.0 hf14f497_3
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libuv 1.44.2 h166bdaf_0
    - libzlib 1.2.13 h166bdaf_4
    - make 4.3 hd18ef5c_1
    - ncurses 6.3 h27087fc_1
    - openssl 3.1.0 h0b41bf4_0
    - rhash 1.4.3 h166bdaf_0
    - sysroot_linux-64 2.12 he073ed8_15
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 h166bdaf_4
    - zstd 1.5.2 h3eb15da_6
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
  run:
    - libgcc-ng >=12
test:
  commands:
    - test -e $PREFIX/include/zlib-ng.h
    - test -e $PREFIX/include/zconf-ng.h
    - test -e $PREFIX/lib/libz-ng${SHLIB_EXT}
    - test -e $PREFIX/lib/pkgconfig/zlib-ng.pc
about:
  home: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE.md
  summary: zlib data compression library for the next generation systems
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
