# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Dec  3 18:34:55 2023
# ------------------------------------------------

package:
  name: libxslt
  version: 1.1.39
source:
  patches:
    - 0001-Make-and-install-a-pkg-config-file-on-Windows.patch
    - 0002-win-profiler-config.patch
  sha256: 2a20ad621148339b0759c4d4e96719362dee64c9a096dbba625ba053846349f0
  url: https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.39.tar.xz
build:
  number: '0'
  run_exports:
    - libxslt >=1.1.39,<2.0a0
  string: h76b75d6_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_3
    - gcc_linux-64 12.3.0 h76fc315_2
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_103
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libsanitizer 12.3.0 h0f45ef3_3
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - make 4.3 hd18ef5c_1
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - icu 73.2 h59595ed_0
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libiconv 1.17 h166bdaf_0
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - libxml2 2.12.1 h232c23b_0
    - libzlib 1.2.13 hd590300_5
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - libxml2 >=2.12.1,<2.13.0a0
test:
  commands:
    - xsltproc --version
    - pkg-config --cflags libxslt libexslt
    - pkg-config --libs libxslt libexslt
  requires:
    - pkg-config
about:
  description: '"Libxslt is the XSLT C library developed for the GNOME project.

    XSLT itself is a an XML language to define transformation for XML.

    Libxslt is based on libxml2 the XML C library developed for the GNOME project.

    It also implements most of the EXSLT set of processor-portable extensions functions

    and some of Saxon''s evaluate and expressions extensions."

    '
  dev_url: https://gitlab.gnome.org/GNOME/libxslt
  doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc
  doc_url: https://gitlab.gnome.org/GNOME/libxslt/-/wikis
  home: https://gitlab.gnome.org/GNOME/libxslt
  license: MIT
  license_file: COPYING
  summary: The XSLT C library developed for the GNOME project
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231203.8.1
  recipe-maintainers:
    - mbargull
    - ocefpaf
    - scopatz
  remote_url: https://github.com/conda-forge/libxslt-feedstock
  sha: e28d71832758fbf146a1dd40f569dc94b2240747
