# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jan  5 01:40:04 2022
# ------------------------------------------------

package:
  name: yaml
  version: 0.2.5
source:
  sha256: fa240dbf262be053f3898006d502d514936c818e422afdcf33921c63bed9bf2e
  url: https://github.com/yaml/libyaml/archive/0.2.5.tar.gz
build:
  number: '2'
  run_exports:
    - yaml >=0.2.5,<0.3.0a0
  string: h7f98852_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - autoconf 2.69 pl5321hd708f79_11
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_3
    - gcc_impl_linux-64 9.4.0 h03d3576_11
    - gcc_linux-64 9.4.0 h391b98a_3
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.4.0 hd854feb_11
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgomp 11.2.0 h1d223b6_11
    - libsanitizer 9.4.0 h79bfe98_11
    - libstdcxx-ng 11.2.0 he4da1e4_11
    - libtool 2.4.6 h9c3ff4c_1008
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 1_h7f98852_perl5
    - sysroot_linux-64 2.12 he073ed8_15
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgomp 11.2.0 h1d223b6_11
  run:
    - libgcc-ng >=9.4.0
test:
  commands:
    - test -f "${PREFIX}/include/yaml.h"
    - test -f "${PREFIX}/lib/libyaml${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/pkgconfig/yaml-0.1.pc"
about:
  description: 'YAML is a human friendly data serialization standard for all programming

    languages.

    '
  dev_url: https://github.com/yaml
  doc_source_url: https://github.com/yaml/www.yaml.org/tree/master/docs
  doc_url: http://www.yaml.org/spec/1.2/spec.html
  home: http://pyyaml.org/wiki/LibYAML
  license: MIT
  license_file: License
  summary: A C library for parsing and emitting YAML
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - seanyen
