# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul 31 13:36:59 2023
# ------------------------------------------------

package:
  name: ipywidgets
  version: 7.8.0
source:
  sha256: 6412eb61d1ccde049f731084266b3c946117b3e8c2769923fc20ea35633ef77c
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-7.8.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/ipywidgets_1690810703375/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv --no-deps
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.42.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.1 hd590300_1
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.11.4 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.0.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - comm >=0.1.3
    - ipython >=4.0.0
    - ipython_genutils >=0.2.0,<0.3.0
    - jupyterlab_widgets >=1.0.0,<3
    - python >=3.3
    - traitlets >=4.3.1
    - widgetsnbextension >=3.6.4,<3.7.0
test:
  commands:
    - pip check
    - pytest -vv --pyargs ipywidgets --cov=ipywidgets --cov-report=term-missing:skip-covered
      --no-cov-on-fail --cov-fail-under=91
  imports:
    - ipywidgets
  requires:
    - ipykernel
    - pip
    - pytest-cov
about:
  description: 'ipywidgets are interactive HTML widgets for Jupyter notebooks and
    the IPython kernel.

    '
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst
  doc_url: https://ipywidgets.readthedocs.io
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Interactive Widgets
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
    - jakirkham
    - jasongrout
    - jtpio
    - maartenbreddels
    - martinRenou
    - minrk
    - pbugnion
    - pelson
    - vidartf
    - willingc
