# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun 17 20:58:21 2024
# ------------------------------------------------

package:
  name: astropy
  version: 6.1.1
source:
  sha256: e5c6f45d911c30acb8d556c7f8ed994aec71b108e61eee5067f00af1e4e36138
  url: https://pypi.io/packages/source/a/astropy/astropy-6.1.1.tar.gz
build:
  entry_points:
    - fits2bitmap = astropy.visualization.scripts.fits2bitmap:main
    - fitscheck = astropy.io.fits.scripts.fitscheck:main
    - fitsdiff = astropy.io.fits.scripts.fitsdiff:main
    - fitsheader = astropy.io.fits.scripts.fitsheader:main
    - fitsinfo = astropy.io.fits.scripts.fitsinfo:main
    - samp_hub = astropy.samp.hub_script:hub_script
    - volint = astropy.io.votable.volint:main
    - wcslint = astropy.wcs.wcslint:main
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/astropy_1718657973352/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: py310h261611a_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_7
    - gcc_impl_linux-64 12.3.0 h58ffeeb_10
    - gcc_linux-64 12.3.0 h9528a6a_7
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.3.0 h6b66f73_110
    - libgcc-ng 13.2.0 h77fa898_10
    - libgomp 13.2.0 h77fa898_10
    - libsanitizer 12.3.0 hb8811af_10
    - libstdcxx-ng 13.2.0 hc0a3c3a_10
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - cython 3.0.10 py310hc6cd4ac_0
    - extension-helpers 1.1.1 pyhd8ed1ab_0
    - jinja2 3.1.4 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libblas 3.9.0 22_linux64_openblas
    - libcblas 3.9.0 22_linux64_openblas
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_10
    - libgfortran-ng 13.2.0 h69a702a_10
    - libgfortran5 13.2.0 h3d2ce59_10
    - libgomp 13.2.0 h77fa898_10
    - liblapack 3.9.0 22_linux64_openblas
    - libnsl 2.0.1 hd590300_0
    - libopenblas 0.3.27 pthreads_h413a1c8_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_10
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - markupsafe 2.1.5 py310h2372a71_0
    - ncurses 6.5 h59595ed_0
    - numpy 2.0.0 py310h515e003_0
    - openssl 3.3.1 h4ab18f5_0
    - packaging 24.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.10.14 hd12c33a_0_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - setuptools_scm 8.1.0 hd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - astropy-iers-data >=0.2024.5.27.0.30.8
    - importlib-metadata
    - libgcc-ng >=12
    - numpy >=1.19,<3
    - numpy >=1.23
    - packaging >=19.0
    - pyerfa >=2.0.1.1
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
    - pyyaml >=3.13
test:
  commands:
    - fits2bitmap --help
    - fitscheck --help
    - fitsdiff --help
    - fitsheader --help
    - fitsinfo --help
    - samp_hub --help
    - volint --help
    - wcslint --help
  imports:
    - astropy
  requires:
    - pytest-astropy
about:
  description: 'The Astropy Project is a community effort to develop a single package
    for

    Astronomy in Python. It contains core functionality and common tools

    needed for performing astronomy and astrophysics research with Python.

    '
  dev_url: https://github.com/astropy/astropy
  doc_url: http://docs.astropy.org/en/stable/
  home: http://www.astropy.org/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Community-developed Python Library for Astronomy
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240617.5.1
  recipe-maintainers:
    - astrofrog
    - bsipocz
    - mwcraig
  remote_url: https://github.com/conda-forge/astropy-feedstock
  sha: e20a4c44fdb9114d280720bcdaab83a9a72b7f9f
