# This file created by conda-build 3.28.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Dec 10 23:11:04 2023
# ------------------------------------------------

package:
  name: pathspec
  version: 0.12.1
source:
  sha256: a482d51503a1ab33b1c67a6c3813a26953dbdc71c31dacaef9a838c4e29f5712
  url: https://pypi.io/packages/source/p/pathspec/pathspec-0.12.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pathspec_1702249949303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - pip 23.3.1 pyhd8ed1ab_0
    - python 3.12.0 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023c h71feb2d_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
    - cd tests && pytest
  imports:
    - pathspec
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'pathspec is a utility library for pattern matching of file paths.
    So far

    this only includes Git''s wildmatch pattern matching which itself is derived

    from Rsync''s wildmatch. Git uses wildmatch for its gitignore files.

    '
  doc_source_url: https://github.com/cpburnz/python-path-specification/blob/master/doc/source/index.rst
  doc_url: https://python-path-specification.readthedocs.io
  home: https://github.com/cpburnz/python-path-specification
  license: MPL-2.0
  license_file: LICENSE
  summary: Utility library for gitignore style pattern matching of file paths.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231210.2.1
  recipe-maintainers:
    - bollwyvl
    - proinsias
  remote_url: https://github.com/conda-forge/pathspec-feedstock
  sha: e7a5f386130644ad62c925610dd9aa7f3d84314f
