# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun May  1 17:17:47 2022
# ------------------------------------------------

package:
  name: sphinx-jsonschema
  version: 1.19.1
source:
  sha256: b2385fe1c7acf2e759152aefed0cb17c920645b2a75c9934000c9c528e7d53c1
  url: https://pypi.io/packages/source/s/sphinx-jsonschema/sphinx-jsonschema-1.19.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/sphinx-jsonschema_1651425532407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_16
    - libgomp 11.2.0 h1d223b6_16
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h166bdaf_1014
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.2 h166bdaf_1
    - pip 22.0.4 pyhd8ed1ab_0
    - python 3.10.4 h2660328_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 62.1.0 py310hff52083_0
    - sqlite 3.38.3 h4ff8645_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h166bdaf_1014
  run:
    - docutils
    - jsonpointer
    - python >=3.6
    - pyyaml
    - requests
    - sphinx
test:
  commands:
    - pip check
    - python -c "import importlib; importlib.import_module('sphinx-jsonschema')"
  requires:
    - pip
about:
  home: https://github.com/lnoor/sphinx-jsonschema
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Sphinx extension to display JSON Schema
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - maresb
