# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Mar 25 23:55:34 2024
# ------------------------------------------------

package:
  name: pytest-cov
  version: 5.0.0
source:
  fn: pytest-cov-5.0.0.tar.gz
  sha256: 5837b58e9f6ebd335b0f8060eecce69b662415b16dc503883a02f45dfeb14857
  url: https://pypi.io/packages/source/p/pytest-cov/pytest-cov-5.0.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pytest-cov_1711411024363/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - coverage >=5.2.1
    - pytest >=4.6
    - python >=3.8
    - toml
test:
  commands:
    - pytest --traceconfig | grep pytest-cov-5.0.0
about:
  dev_url: https://github.com/pytest-dev/pytest-cov
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for measuring coverage
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240325.2.1
  recipe-maintainers:
    - dopplershift
    - nicoddemus
  remote_url: https://github.com/conda-forge/pytest-cov-feedstock
  sha: bb80df427d95e828bfad40426b7776dcc6cad814
