# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Apr 24 16:07:23 2024
# ------------------------------------------------

package:
  name: tinycss2
  version: 1.3.0
source:
  sha256: 152f9acabd296a8375fbca5b84c961ff95971fcfc32e79550c8df8e29118c54d
  url: https://pypi.io/packages/source/t/tinycss2/tinycss2-1.3.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/tinycss2_1713974937325/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotli-python 1.1.0 py312h30efb56_1
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - certifi 2024.2.2 pyhd8ed1ab_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - docutils 0.21.2 pyhd8ed1ab_0
    - exceptiongroup 1.2.0 pyhd8ed1ab_2
    - flit 3.9.0 pyhd8ed1ab_1
    - flit-core 3.9.0 pyhd8ed1ab_1
    - idna 3.7 pyhd8ed1ab_0
    - iniconfig 2.0.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 hc881cc4_6
    - libgomp 13.2.0 hc881cc4_6
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libstdcxx-ng 13.2.0 h95c4c6d_6
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - pytest 8.1.1 pyhd8ed1ab_0
    - pytest-runner 6.0.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - requests 2.31.0 pyhd8ed1ab_0
    - setuptools 69.5.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tomli-w 1.0.0 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - urllib3 2.2.1 pyhd8ed1ab_0
    - webencodings 0.5.1 pyhd8ed1ab_2
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.5
    - webencodings >=0.4
test:
  imports:
    - tinycss2
about:
  description: 'tinycss2 is a rewrite of tinycss with a simpler API, based on the
    more recent

    CSS Syntax Level 3 Specification.

    '
  dev_url: https://github.com/Kozea/tinycss2
  doc_url: http://tinycss2.readthedocs.io
  home: https://github.com/Kozea/tinycss2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Low-level CSS parser for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240424.2.1
  recipe-maintainers:
    - johanneskoester
    - mrandrewandrade
    - thewchan
  remote_url: https://github.com/conda-forge/tinycss2-feedstock
  sha: 867c3edd908d5290130f183349bce8c8165ffe46
