# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun 17 11:57:27 2024
# ------------------------------------------------

package:
  name: sympy
  version: 1.12.1
source:
  sha256: 2877b03f998cd8c08f07cd0de5b767119cd3ef40d09f41c30d722f6686b0fb88
  url: https://pypi.io/packages/source/s/sympy/sympy-1.12.1.tar.gz
build:
  entry_points:
    - isympy = isympy:main
  noarch: python
  number: '3'
  script: /home/conda/feedstock_root/build_artifacts/sympy_1718625546171/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyh04b8f61_3
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_6
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_10
    - libgomp 13.2.0 h77fa898_10
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - mpmath 1.3.0 pyhd8ed1ab_0
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.4 h194c7f8_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - mpmath >=0.19
    - python >=3.8
test:
  commands:
    - isympy --help
  imports:
    - sympy
about:
  description: 'SymPy is a Python library for symbolic mathematics. It aims to become
    a

    full-featured computer algebra system (CAS) while keeping the code as

    simple as possible in order to be comprehensible and easily extensible.

    '
  dev_url: https://github.com/sympy/sympy
  doc_source_url: https://github.com/sympy/sympy/tree/master/doc
  doc_url: https://docs.sympy.org/latest/index.html
  home: https://sympy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for symbolic mathematics
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240617.1.1
  recipe-maintainers:
    - asmeurer
    - isuruf
    - msarahan
    - scopatz
  remote_url: https://github.com/conda-forge/sympy-feedstock
  sha: 9db57fd09c110f1962b141d7a722d95f54cab7a1
