# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct  1 11:40:40 2023
# ------------------------------------------------

package:
  name: libgd
  version: 2.3.3
source:
  patches:
    - patches/linux-fontconfig-basic.patch
  sha256: 24429f9d0dbe0f865aaa4b1a63558242396ba9134e6cfd32ca5e486a84483350
  url: https://github.com/libgd/libgd/archive/gd-2.3.3.tar.gz
build:
  number: '9'
  run_exports:
    - libgd >=2.3.3,<2.4.0a0
  string: h119a65a_9
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_2
    - gcc_linux-64 12.3.0 h76fc315_2
    - gettext 0.21.1 h27087fc_0
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_2
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libnsl 2.0.0 hd590300_1
    - libsanitizer 12.3.0 h0f45ef3_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - libtool 2.4.7 h27087fc_0
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 4_hd590300_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - expat 2.5.0 hcb278e6_1
    - fontconfig 2.14.2 h14ed4e7_0
    - freetype 2.12.1 h267a509_2
    - giflib 5.2.1 h0b41bf4_3
    - icu 73.2 h59595ed_0
    - lerc 4.0.0 h27087fc_0
    - libdeflate 1.19 hd590300_0
    - libexpat 2.5.0 hcb278e6_1
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libjpeg-turbo 3.0.0 hd590300_1
    - libpng 1.6.39 h753d276_0
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - libtiff 4.6.0 ha9c0a0a_2
    - libuuid 2.38.1 h0b41bf4_0
    - libwebp 1.3.2 h658648e_1
    - libwebp-base 1.3.2 hd590300_0
    - libzlib 1.2.13 hd590300_5
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
    - zstd 1.5.5 hfc55251_0
  run:
    - expat
    - fontconfig >=2.14.2,<3.0a0
    - fonts-conda-ecosystem
    - freetype >=2.12.1,<3.0a0
    - icu >=73.2,<74.0a0
    - libexpat >=2.5.0,<3.0a0
    - libgcc-ng >=12
    - libjpeg-turbo >=3.0.0,<4.0a0
    - libpng >=1.6.39,<1.7.0a0
    - libtiff >=4.6.0,<4.7.0a0
    - libwebp
    - libwebp-base >=1.3.2,<2.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - zlib
test:
  commands:
    - test -f $PREFIX/lib/libgd.a
    - test -f $PREFIX/lib/libgd${SHLIB_EXT}
about:
  home: http://libgd.github.io/
  license: GD
  license_family: BSD
  license_file: COPYING
  summary: Library for the dynamic creation of images
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ChrisBarker-NOAA
    - croth1
    - ocefpaf
