# This file created by conda-build 3.28.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Dec 12 16:41:45 2023
# ------------------------------------------------

package:
  name: prompt-toolkit
  version: 3.0.42
source:
  sha256: bfbf7d6ea9744e4ec94c9a69539e8106c77a2a607d728ded87c9182a4aec39be
  url: https://pypi.io/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.42.tar.gz
build:
  noarch: python
  number: '0'
  string: pyha770c72_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - pip 23.3.1 pyhd8ed1ab_0
    - python 3.12.0 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023c h71feb2d_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
    - wcwidth
  run_constrained:
    - prompt_toolkit 3.0.42
about:
  description: 'prompt_toolkit is a library for building powerful interactive command

    lines and terminal applications in Python. It can be a pure Python

    replacement for GNU readline, but it can be much more than that.

    '
  dev_url: https://github.com/jonathanslenders/python-prompt-toolkit
  doc_url: http://python-prompt-toolkit.readthedocs.io
  home: https://github.com/jonathanslenders/python-prompt-toolkit
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Library for building powerful interactive command lines in Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231212.2.1
  recipe-maintainers:
    - asmeurer
    - jakirkham
    - ocefpaf
    - scopatz
  remote_url: https://github.com/conda-forge/prompt_toolkit-feedstock
  sha: 1f155c787702e099272c7e1a1c548cd346d77773
