# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Apr  5 12:31:27 2024
# ------------------------------------------------

package:
  name: parso
  version: 0.8.4
source:
  fn: parso-0.8.4.tar.gz
  sha256: eb3a7b58240fb99099a345571deecc0f9540ea5f4dd2fe14c2a99d6b281ab92d
  url: https://pypi.io/packages/source/p/parso/parso-0.8.4.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/parso_1712320355065/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.6
test:
  imports:
    - parso
    - parso.pgen2
    - parso.python
about:
  description: 'Parso is a Python parser that supports error recovery and round-trip
    parsing for different Python versions (in multiple Python versions).

    Parso is also able to list multiple syntax errors in your python file.

    '
  dev_url: https://github.com/davidhalter/parso
  doc_url: https://parso.readthedocs.io/en/latest/
  home: https://github.com/davidhalter/parso
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Parser
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240405.2.1
  recipe-maintainers:
    - iron0012
    - synapticarbors
  remote_url: https://github.com/conda-forge/parso-feedstock
  sha: 83d25012b019d85265ebfb2249794d82e9cc4a12
